super-linter/super-linter

lib/linter.sh

Setting path for possum.sh since we've moved it to /action

set path for possum

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/general-question.md

Adding issue templates to help contributors create higher quality issues.

Create issue templates

---

README.md

- Making the env vars more readable

make the readme better

---

docs/run-linter-locally.md

even better

---

README.md

Switch to versioned pointer from pointing people to the latest so they don't get unexpected or unstable behavior.

Switch to versioned docker container example

---

.github/CONTRIBUTING.md
README.md

Set v2 in example workflow and update release  procedure to cover docs
Signed-off-by: Zack Koppert <zkoppert@github.com>

Update docs to v2

---

Dockerfile
lib/.npmrc

- Cleanup of **NPM** Installs
- Cleanup of **Python** Installs
- Cleanup of **APK** Installs
- Cleanup of **Gem** installs
- Cleanup of **curl** and **wget**
This closes #102

Cleanup Of Log Files

---

.automation/cleanup-docker.sh

This PR will cover:
- Not failing the cleanup step when merging a PR that was a fork
- Since the fork is not in the Org/Repo, we cant pull secrets, which breaks the step, but also, we never formally build the test container, so there is no cleanup to complete...

fixing automation

---

README.md
action.yml

Fix typo (combination on → combination of)

---

.automation/cleanup-docker.sh
.automation/upload-docker.sh
.github/workflows/deploy-DEV.yml
.github/workflows/deploy-PROD.yml
.github/workflows/stack-linter.yml

This PR will cover:
- Moving the underlying image from `admiralawkbar` to `GitHub` on **Docker**

Changing from Admiralawkbar to github

---

.automation/cleanup-docker.sh
.automation/test/ansible/ghe-initialize/defaults/main.yml
.automation/test/ansible/ghe-initialize/tasks/ghe-initial-configuration.yml
.automation/test/python/python_bad_1.py
.automation/test/python/python_good_1.py
.automation/upload-docker.sh
Dockerfile
lib/linter.sh

Rename **Github** to **GitHub**.
Uses:
```sh
git grep -l 'Github' | xargs sed -i '' -e 's/Github/GitHub/g'
```
Signed-off-by: Antoine Leblanc <ant.leblanc@gmail.com>

Minor brand wording change

---

README.md
docs/run-linter-locally.md
lib/linter.sh

This will give more flexibility to anyone who doesn't happen to keep their files in `/tmp/lint` and is running it locally.

Default workspace

---

.automation/test/css/README.md
.automation/test/css/css_bad_01.css
.automation/test/css/css_good_01.css
.github/linters/.stylelintrc.json
Dockerfile
README.md
TEMPLATES/.stylelintrc.json
docs/disabling-linters.md
lib/linter.sh

Added tests
Updated readme with usage notes (disabling lines etc) to match existing
content

Add stylelint support to super-linter

---

README.md
TEMPLATES/README.md

- Updating documentation to point to use the **Docker** container
- It's much faster to download than to build...

fixing docs to point to Docker

---

lib/linter.sh

Looks the new CSS and ENV incorporation was missing a few characters :)

Add missing closing curly brackets

---

.automation/README.md

Fixes a couple of typos in `.automation/README.md`.

Fix some typos

---

.github/ISSUE_TEMPLATE/feature_request.md

This will help guide users from request to contribution and give a framework to understand what a new language might include.

Add link to wiki for new language support

---

.github/CONTRIBUTING.md

Rounding out more steps to the release instructions to include publishing docker images.

More complete release instructions

---

.automation/upload-docker.sh
.github/CONTRIBUTING.md
.github/workflows/deploy-DEV.yml
.github/workflows/deploy-PROD.yml
.github/workflows/deploy-RELEASE.yml

- Adding GitHub Actions for Release deployment

Adding deploy For releases

---

.github/workflows/deploy-RELEASE.yml

Release typo

---

lib/linter.sh

This should solve a bug with folders on `powershell` and some hard coding of `ansible`
Closes #260

fixed ansible and powershell

---

.devcontainer/devcontainer.json
.gitattributes
.vscode/launch.json
.vscode/testlinter.sh
README.md
lib/linter.sh

Dev: Add Visual Studio Code + Github Codespaces Support

---

lib/linter.sh

- Fixing issue with files with space chars breaking when found
closes #276

Adding space support

---

.github/CONTRIBUTING.md

This updates the `CONTRIBUTING.md` to add a step to ensure we release to the GitHub Marketplace as well to update that listing.
/cc @zkoppert as you asked me for this 😋

Add step to ensure release is on marketplace

---

README.md

This updates the README to point to `v3` tag.

Update docs to point to v3

---

.automation/upload-docker.sh

fixed GPR typo

---

.automation/upload-docker.sh
lib/linter.sh

Adding logic to also deploy docker tags to major versions

adding logic to deploy major tag versions as well

---

.github/CONTRIBUTING.md

Only change the wiki and `README.md` version numbers if it is a major revision

no doc changes on release unless major update

---

.automation/upload-docker.sh
Dockerfile

use last version available
this closes #317 
this closes #314

bump CLJ_KONDO_VERSION

---

README.md

making the `readme` easier to read

make easier to read

---

lib/linter.sh

Don't show shyaml errors to the console

---

Dockerfile

DockerFile: Add missing AllUsers Scope when install PSSA

---

.automation/test/ansible/ghe-initialize/templates/ghe-config-apply.sh
.automation/upload-docker.sh
.vscode/testlinter.sh
lib/buildFileList.sh
lib/linter.sh
lib/worker.sh

This closes #324 
Ref: https://github.com/github/super-linter/pull/239 and https://github.com/github/super-linter/pull/241
This has been rebased on the current (as of creating) master.

Shell check

---

README.md

- Format how to into numbered steps
- Add gif to show people the way
resolves #218

Quickstart

---

.github/workflows/deploy-DEV.yml
README.md
TEMPLATES/.tflint.hcl
lib/buildFileList.sh
lib/linter.sh

This closes #339 
This closes #340
This closes #320
This closes #282 
This closes #349

Were going to fix it all

---

lib/worker.sh

This PR will try to solve the Powershell exit early bug

fixed early exit

---

lib/worker.sh

Reverts github/super-linter#357

Revert "fixed early exit"

---

lib/linter.sh
lib/worker.sh

See https://github.com/github/super-linter/issues/334#issuecomment-653196388
https://github.com/koalaman/shellcheck/blob/5a42f4b938f509090d0b8c75523d83e24466dab4/shellcheck.1.md#options

Add color flag for shellcheck

---

.github/release-drafter.yml

No related issue
- Change language in releases to reference the "previous" release instead of the "latest" since that is not always true

Correct release compare language

---

lib/buildFileList.sh

This closes #407 
this throws the fun little error message but also fixes the refs...
may need to find a better path eventually

fine well do it this way

---

.github/workflows/draft-release.yml.hold

- Need to put hold on release drafter as it breaks automation for release deploy

adding hold

---

.github/CONTRIBUTING.md
README.md

Detail out options for running outside GitHub Actions
- Add Azure article reference
- Add GitLab snippet reference
- Move CI/CT/CD section to `CONTRIBUTING.md` since only contributors will find relevant

Add Azure and Gitlab options

---

Dockerfile
dependencies/Gemfile
dependencies/Gemfile.lock
lib/linter.sh

This closes #234 
This updates and fixes the Ruby dependencies, and added a flag to ignore files from ruby exclude

fixing ruby

---

Dockerfile

This will install the `Raku` and `Zef` as APK packages and bring down the build time significantly...
Hopefully, all tests work :)

BetterRaku

---

.github/workflows/automerge-dependabot.yml

This will help make sure we're always up to date and taking in the latest security issues

Automerge Dependabot dependencies

---

.github/CODEOWNERS

New maintainers should be listed as codeowners
1. Add new codeowners

Add new community maintainers

---

dependencies/Pipfile
dependencies/Pipfile.lock
lib/linter.sh

This closes #432 
`shyaml` was being called to parse Jinja formats and causing parsing errors... This was better done with grep

fix shyaml

---

Dockerfile
lib/linter.sh

This closes #493 
Small logic issues needed to be checked

Fixed logic

---

.github/workflows/automerge-dependabot.yml

Need to fix the default token so that auto-merge can make updates as needed :)

fix default token

---

.github/workflows/automerge-dependabot.yml

remove the token for automerge...

no token needed

---

lib/linter.sh

this fixes what i forgot to merge...

Fix Hadolint

---

.github/CODEOWNERS
.github/workflows/automerge-dependabot.yml

This should hopefully fix the auto-merge for `dependabot` and allow it to merge the small fixes

Fix auto again

---

lib/linter.sh

Fixes https://github.com/github/super-linter/issues/491
1. Add editorconfig to the list of languages
2. Add variables for editorconfig errors

Editorconfig error reporting fix

---

.github/workflows/deploy-DEV-PR.yml

This will help resolve the auto-merge issues of having multiple checks on the same name.

Fixing Actions job name

---

lib/linter.sh

Fixes https://github.com/github/super-linter/issues/543
1. Add missing entry to array

Add missing editorconfig-checker to linter array

---

README.md

Fixes #533
Adds a bit more explanation of why the GTIHUB_TOKEN variable is recommended, and what it is used for.

Explain GitHub token a bit more

---

.github/linters/.sql-config.json
TEMPLATES/.sql-config.json
dependencies/package-lock.json
dependencies/package.json
docs/disabling-linters.md
lib/linter.sh
lib/worker.sh

Fixes #538 
- Upgrade dependency to npm-groovy-lint@7.2.0 : it has better performances
- Upgrade dependency to sql-lint@0.0.15 : npm install works on Windows (after fix of https://github.com/joereynolds/sql-lint/issues/157 )
Only the fixes upper

Upgrade npm-groovy-lint@7.2.0 and sql-lint@0.0.15

---

lib/linter.sh

small version fix
this closes #543

smallFix on editorconfig

---

lib/buildFileList.sh
lib/linter.sh
lib/worker.sh

1. Add sass and scss files to be linted by stylelint
2. ...
3. ...

Add sass and scss files to stylelint

---

.automation/test/docker/good/Dockerfile.dev
Dockerfile
lib/buildFileList.sh

This closes #558 
- Adding more logic to catch additional `dockerfiles`
- Adding a test

adding more tests and cool logic

---

.github/workflows/automerge-dependabot.yml

Needed to wait for super linter to finish

adding more logic

---

.automation/upload-docker.sh

This PR includes:
- Pushing to the new location...

Push to new GitHub Container Registry

---

lib/linter.sh

This closes #589 
- Bug ion logic allows you to get into Status API call with no Token... Should resolve that

fix logic hole

---

README.md

- Just some simple cleanup of `README.md` that's been bothering me...

some simple cleanup

---

.automation/upload-docker.sh
.github/workflows/deploy-PROD.yml
.github/workflows/deploy-RELEASE.yml
lib/linter.sh

- This will help deploy code faster and update some language

Adding better deployment code

---

lib/buildFileList.sh

This closes #603 
- Adding language info for `zsh` and loop room to kick it out... until we have a better solution for it

adding some spaget

---

.automation/upload-docker.sh

- I didn't like the logic on the old way and this seems a little better... Probably more room for improvement, but we can enjoy faster build times with this

better code

---

README.md

Fixes #
1.  Fix  typo - Github -> GitHub 
2. ...
3. ...

fix(readme): typo - Github -> GitHub 

---

Dockerfile

- Need to add apk `file` to allow us to try to find file types
this was removed by error some time ago...
This closes #612

add file back

---

lib/linter.sh

This closes #629 
- Typo in the name of the file

Fix Coffeescript

---

lib/buildFileList.sh
lib/linter.sh

- Better loop to prevent false positives when sending information back on the status api
- This should help remove false reporting

better loop

---

lib/buildFileList.sh
lib/worker.sh

This closes #603
- Need to really cleanup order of worker and add fix to exclude zsh scripts

lots of cleanup

---

.automation/upload-docker.sh

- Small logic issue in deploy latest

Fixing deploy latest

---

Dockerfile

- Docs:
- https://github.com/opencontainers/image-spec/blob/master/annotations.md#pre-defined-annotation-keys

adding more info

---

.automation/upload-docker.sh
Dockerfile

- Adding dynamic vars to the deployment of the containers
- It's pretty cool

Adding more vars

---

dependencies/package-lock.json
dependencies/package.json
lib/buildFileList.sh
lib/linter.sh
lib/worker.sh

- GROOVYLINT:  lint [nextflow](https://www.nextflow.io/) files, as they are written in groovy (extension: .nf )
- GROOVYLINT: upgrade [npm-groovy-lint](https://github.com/nvuillam/npm-groovy-lint) to latest version

Groovy traps .nf extension (nextflow) + upgrade npm-groovy-lint

---

.github/workflows/stack-linter.yml
action.yml

1. Uses GitHub Container Registry in action.yml ([dogfooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food))

Move to GitHub Container Registry

---

lib/linter.sh
lib/worker.sh

Fix file filters: Reorder arguments to LintCodeBase function

---

docs/disabling-linters.md

Fix for Javascript capitalization

Fix JavaScript capitalizaton

---

Dockerfile

This closes #724 
We need to pull from versions and not the latest from the docker layers
This should help us version the information

adding version

---

README.md

I think it probably makes more sense for the examples in this README to follow YAML syntax, assuming that people will be running super-linter as a GitHub Action. There's a separate doc covering the process for running the linter locally, in which case, of course, environment variables would be set with an equals sign. It's not a big deal (and no worries about closing the PR on grounds of triviality), but I thought I would make the suggestion.

Use YAML syntax in FILTER_REGEX examples

---

Dockerfile

Move images to GHCR

---

dependencies/Pipfile
dependencies/Pipfile.lock

This closes #762 
Seems black was downgraded again.. need to keep an eye on this

fix version

---

docs/disabling-linters.md

- Fix doc on hadolint ignore rule

adding rules

---

lib/buildFileList.sh

- Add a warning to linter when no files are found to lint

add warning:

---

TEMPLATES/.ecrc

Fixes #858 
1. ...
2. ...
3. ...

Create template .ecrc

---

docs/disabling-linters.md

Fixes #
Explain the content of `.github/linters/.markdown-lint.yml` file.
1. ...
2. ...
3. ...

docs: explain markdownlint yaml configuration file

---

docs/disabling-linters.md

docs: add terragrunt link in table of linters

---

lib/worker.sh

Fix test case workspace_path

---

lib/linter.sh

This should help fix the linter rules logic issues

fixing logic

---

.github/workflows/deploy-DEV.yml

- Need to change echo as its no longer supported

fixThatEcho

---

.github/workflows/deploy-PROD.yml
.github/workflows/deploy-RELEASE.yml

- This is the right way to do this
- Better deployment
- cleaner tagging
- overall I dig it

much better

---

.github/workflows/deploy-PROD.yml
.github/workflows/deploy-RELEASE.yml

Better deploy

---

lib/functions/buildFileList.sh

Fixes #1074
1. Fix for checking openapi yaml/yml files

Check OpenAPI yaml files

---

lib/functions/buildFileList.sh

this closes #1113
Adding additional checks to make sure we don't grab extra files hen hunting for docker

fix logic for docker

---

.automation/test/arm/arm_bad_1.json

Fixes
1. Fix error on test because deprecated arm template schema

Update arm template

---

.automation/test/go/reports/expected-GO.tap
dependencies/package-lock.json
dependencies/package.json

1. Allows using some extra plugins for stylelint

Add extra stylelint sass dependencies

---

Dockerfile

Fixes clj kondo version stalled
1. Update to use new alpine image of clj condo from https://github.com/clj-kondo/clj-kondo/issues/1106

Update to use clj kondo alpine image

---

.github/workflows/stack-linter.yml
action.yml

Fixes #490 
1. Make the action.yml reflect the exact current version instead of only the major version tag.

testing versioning

---

.automation/trivy-security-scan.sh

- Only error high and critical issues
This will still show any issues that were found, but only exit `1` when a new high or critical issue is found

only show high and critical

---

.automation/update-actions-version.sh
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/CREATE_RELEASE.md
.github/workflows/deploy-RELEASE.yml
dependencies/package-lock.json
dependencies/package.json

This will help solve the release process for the GitHub Super-Linter
- We now can create releases from Issues in the repository
- It will notify the issue it has seen the information and starts the Actions job
- It will create a branch and update the `actions.yml` with the new version supplied to the issue
- It will then create a PR with the updated code
- It will then create the release and build the artifacts needed
- it will then publish the release and merge the PR

Adding release process

---

lib/functions/buildFileList.sh

Fixes #1258
1. Added logic to run the command and check for errors, before mapping the files to an array, to avoid silent failures of the commands.

Add logic to check command output before maping the files

---

.automation/update-actions-version.sh
.github/workflows/deploy-RELEASE.yml

fixed deploy

---

.automation/update-actions-version.sh
.github/workflows/deploy-RELEASE.yml

Getting sha info to help pass status check

adding sha info

---

README.md
TEMPLATES/linter.yml

close #1231 
- Adding default `linter.yml` to templates for users to pull down and push to their new repos

Add template

---

lib/functions/buildFileList.sh
lib/linter.sh

Fixes #
1. Fix diff for or event.
2. Also we don't need to checkout the main branch. The diff commands work fine being in the same brnach.

Fix get file diff on pr event

---

lib/functions/buildFileList.sh

Fix buggy diff cmd

---

.github/workflows/deploy-PROD.yml
.github/workflows/deploy-RELEASE.yml

- Fixing the deployment api and making deployments prettier...

adding dope code

---

.github/workflows/trivy.yml
Dockerfile

Fixes #
1. Add netmask to Dockerfile explicitly so latest version is fetched

Reinstate Trivy with no blocks for vulnerabilities found

---

Dockerfile

- This pulls in the rust layer
- Shrinking that image... 1 layer at a time

pull rust in

---

Dockerfile

- Pull in the `microsoft` layer
- smaller onion layers

pull in ms

---

Dockerfile

- Just shrinking that image...

cleanup node dir

---

.automation/upload-docker.sh
.automation/validate-docker-labels.sh
.github/workflows/deploy-DEV.yml
.github/workflows/deploy-PROD.yml
.github/workflows/draft-release.yml
Dockerfile
action.yml
lib/functions/log.sh
lib/linter.sh

- Small automation fixes
- pull-in Lintr directly to new image

adding fixes

---

.github/workflows/deploy-RELEASE.yml

- Added `--fail` to Create PR call
- Conformed string to single line for `curl`

fix the string to one liner

---

.github/workflows/deploy-PROD.yml
.github/workflows/deploy-RELEASE.yml

- need to bump version in release pipeline

bump version

---

.github/workflows/deploy-PROD-slim.yml
.github/workflows/deploy-PROD-standard.yml
.github/workflows/deploy-RELEASE-slim.yml
.github/workflows/deploy-RELEASE-standard.yml

Thir PR will solve some deployment issues:
- Splitting the `slim` and `standard` image in **prod**
- Splitting the `slim` and `standard` in **release**

split it up

---

README.md
TEMPLATES/linter.yml

This closes #1596
Thanks @TomerFi for the catch!

fix slim docs

---

README.md

What do folks think about including some live year over year activity on the `README.md` so folks can tell that this is an active repository? Is this the right location on the `README.md` or should it be higher?
1. Add community activity stats (YoY)

Add community activity stats

---

lib/functions/detectFiles.sh

This closes #1600 
- Seems an error in the code that didn't properly check for ansible files
- Now we search properly to add files to the array

wildcard search for ansible

---

.github/stale.yml

- Adding stale config to stop the closing of some issues

adding stale config

---

dependencies/package-lock.json
dependencies/package.json

adding vue

---

Dockerfile
Dockerfile-slim
dependencies/Pipfile
dependencies/Pipfile.lock

- move black back to pip as we have a lib issue

move black back to pip

---

.devcontainer/README.md
.devcontainer/devcontainer.json

Fixes no reported issue.
1. Improve a few tidbits around the dev container definition.
Docs aren't needed, the feature isn't critical and quite self-explanatory to its users.

Update, clean up VS Code dev container definition

---

README.md

1. Linked to the example `TEMPLATES/linter.yml` file with a relative path (so it works outside of GitHub too)
2. Changed the example in the README to the content of `/TEMPLATES/linter.yml`

Editorial: linked the example `linter.yml` file, added example form that file

---

.github/linters/.golangci.yml
TEMPLATES/.golangci.yml

fixed go issues

---

.github/workflows/deploy-DEV-slim.yml
.github/workflows/deploy-DEV-standard.yml
.github/workflows/stack-linter.yml

I fix errors caused by switching master to main ( https://github.com/github/super-linter/pull/2010 ).

Fix errors by switching to main branch

---

README.md

Lowercases "And" in the middle of a sentence in README.md.

Trivial fix to README.md

---

README.md

1. Changed broken link from https://github.com/psf/black/blob/master/docs/compatible_configs.md to https://github.com/psf/black/blob/main/docs/guides/using_black_with_other_tools.md#black-compatible-configurations
2. Changed broken link from https://pycqa.github.io/isort/docs/configuration/config_files/ to https://pycqa.github.io/isort/docs/configuration/config_files.html
3. Updated branch name references from master to main

Updated README links

---

Dockerfile
Dockerfile-slim

- Update shfmt from v3.3.1 to v3.4.0

Update shfmt from v3.3.1 to v3.4.0

---

Dockerfile
Dockerfile-slim

Simplify GitLeaks install process, make the image smaller and the build process faster

Simplify GitLeaks install process

---

Dockerfile
Dockerfile-slim

Bumping the binary which doesn't get automatic updates.
Releases notes: [link](https://github.com/psf/black/releases/tag/21.10b0).

Update black binary to 21.10b0

---

Dockerfile
Dockerfile-slim

This closes #2153 
Seems Go needed a new lib now :(

adding lib

---

Dockerfile
Dockerfile-slim

Release reference:
https://github.com/psf/black/releases/tag/21.11b1

Update black binary to 21.11b1

---

Dockerfile
Dockerfile-slim

This closes #2175 
Moving from download to container for dependabot to update :)

move to docker

---

.automation/test/rust_2021/rust_bad_1.rs
.automation/test/rust_2021/rust_good_1.rs
lib/functions/buildFileList.sh

1. Add missing RUST_2021 test.
1. Fix RUST_2021 file list.

Add RUST_2021 test and fix RUST_2021 file list

---

.github/dependabot.yml
.github/linters/.cfnlintrc.yml
.github/linters/.eslintrc.yml
.github/linters/.golangci.yml
.github/linters/.protolintrc.yml
.github/linters/.yaml-lint.yml
.github/release-drafter.yml
.github/workflows/deploy-DEV-slim.yml
.github/workflows/stack-linter.yml
TEMPLATES/.cfnlintrc.yml
TEMPLATES/.eslintrc.yml
TEMPLATES/.golangci.yml
TEMPLATES/.protolintrc.yml
lib/functions/buildFileList.sh

This closes #2273 
- Adding extension `.sc` for scala to pull

Update additional scala extensions

---

.github/CODEOWNERS
.github/workflows/deploy-PROD-slim.yml
.github/workflows/deploy-PROD-standard.yml
.github/workflows/deploy-RELEASE-slim.yml
.github/workflows/deploy-RELEASE-standard.yml

welcome brett

---

Dockerfile
dependencies/package-lock.json
dependencies/phive.xml

Update PHP deps

---

lib/functions/detectFiles.sh

This closes #2357 
- Adding `perl` and `python` to  `file` find

adding perl and python

---

dependencies/package-lock.json
dependencies/package.json

this closes #2339
Adding more libs

adding libs

---

lib/functions/linterVersions.sh

See https://github.com/zricethezav/gitleaks#usage and
https://github.com/rasa/scoop-directory/runs/4883841409?check_suite_focus=true#step:4:139

fix: Output gitleaks version

---

.github/workflows/deploy-Production.yml
.github/workflows/deploy-Release.yml

- Adding checks if push to main to skip tests, and fix docker push issue

cant do load and push, skipping for prod

---

.github/workflows/deploy-Production.yml

- Remove the docker caching as its pretty prone to failure...
- Update codacy to continue on error as it cant reach a secret if kicked by a random user

fix codacy and remove cache as its prone to fail

---

Dockerfile
TEMPLATES/.scalafmt.conf
dependencies/Gemfile
dependencies/Gemfile.lock

update extra deps

---

README.md

Update example config to use actions/checkout@v3

Update example config to use actions/checkout@v3

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-release.yml

https://github.com/github/super-linter/runs/5543578921?check_suite_focus=true
```
/home/runner/work/_actions/bobheadxi/deployments/v1.1.0/webpack:/@bobheadxi/deployments/node_modules/@actions/core/lib/core.js:110
throw new Error(`Input required and not supplied: ${name}`);
^
Error: Input required and not supplied: env
at getInput (/home/runner/work/_actions/bobheadxi/deployments/v1.1.0/webpack:/@bobheadxi/deployments/node_modules/@actions/core/lib/core.js:110:1)
at getRequiredInput (/home/runner/work/_actions/bobheadxi/deployments/v1.1.0/webpack:/@bobheadxi/deployments/src/lib/input.ts:18:1)
at collectDeploymentContext (/home/runner/work/_actions/bobheadxi/deployments/v1.1.0/webpack:/@bobheadxi/deployments/src/lib/context.ts:29:1)
at context …
```

Add parameter env to step Update deployment status

---

.automation/test/ansible/roles/ghe_initialize/handlers/main.yml
.automation/test/ansible/roles/ghe_initialize/tasks/collectd-settings.yml
.automation/test/ansible/roles/ghe_initialize/tasks/ghe-api-config-apply.yml
.automation/test/ansible/roles/ghe_initialize/tasks/ghe-config-apply.yml
.automation/test/ansible/roles/ghe_initialize/tasks/ghe-initial-configuration.yml
.automation/test/ansible/roles/ghe_initialize/tasks/ghe-ldap-configuration.yml
.automation/test/ansible/roles/ghe_initialize/tasks/main.yml
.automation/test/ansible/roles/ghe_initialize/tasks/splunk-settings.yml

1. Fix Ansible tests. Ansible Lint recommends to use the fully qualified module name for builtin modules.

Fix Ansible tests

---

.github/workflows/deploy-release.yml

- Manual trigger for release if something goes wrong

manual trigger

---

dependencies/package-lock.json
dependencies/package.json

- Adding airbnb for typescript
This closes #2676

adding airbnb

---

lib/functions/detectFiles.sh

This closes #2606 
- Added code to see if were linting `tflint` and have files, then run `tflint --init`

adding addional command

---

Dockerfile

I remove one of `go` packages because it is duplicated.

Remove a duplicated package

---

.github/workflows/deploy-production.yml
lib/functions/buildFileList.sh

- Solve issue with safe workspace

adding safe

---

lib/functions/buildFileList.sh

dumb issue

---

Dockerfile

Use canonical method to retrieve Jar file

---

Dockerfile

Fixes #2955
1. Update to new terrascan docker image and latest version

Update terrascan to tenable/terrascan:1.15.1

---

lib/functions/detectFiles.sh

This closes #2954 
- Adding log level to output when we run `ACTIONS_RUNNER_DEBUG=true`
- more?

adding log level

---

.automation/test/kotlin/kotlin_good_1.kt
.automation/test/kotlin_android/kotlin_android_good_1.kt

fix kotlin

---

README.md

1. use latest version of `actions/checkout` in README example

use latest version of `actions/checkout` in README example

---

docs/run-linter-locally.md

This adds 4 example files to the local README to do a shared env file.
This is much simpler then adding support directly that I tried in PR #3270.
Fixes: #2851

Add examples for using a shared env file and related STRTA scripts

---

docs/release-process.md

1. Update the release instructions with details about how the `latest` and `vMAJOR` tags are created.

Update release instructions with details about Git tags

---

action.yml
slim/action.yml

Bump diddy

---

.github/workflows/deploy-release.yml

Fixes #3416
Fixes #3417
1. Check if the value of `RELEASE_VERSION` matches with the semantic version regex after assigning it.

Check the semver pattern after setting the value

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-release.yml

Add explicit permissions for Actions

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-release.yml
Dockerfile
TEMPLATES/.scalafmt.conf
dependencies/Gemfile
dependencies/Gemfile.lock

Bulk update deps

---

dependencies/package-lock.json

Fix JSON security flaw in npm

---

slim/README.md

Fixes #
1. updates docs reference in `slim/README.md` to reflect availability of `slim-v5` 
2. adds closing code fence

updates `v4` references to `v5` in `slim` example

---

.automation/test/arm/README.md
.automation/test/arm/arm_bad_1.json
.automation/test/arm/arm_good_1.json

API versions older than 2 years are treated as errors by the ARM linter.
1. Update ARM tests with newest API version

Updates ARM template API version

---

README.md

Fixes #3986
Fix badging in the README including instructions
1. Fix badging in the README including instructions

Fix badging in the README

---

.github/workflows/cd.yml

Fixes #
1. Fix one part of deploys by updating the ghcr docker image push

change ghcr to super-linter/super-linter

---

.github/workflows/cd.yml

remove dockerhub push for now

---

.github/workflows/cd.yml

Fix a typo in the assignees in the CD pipeline

Fix typo in CD pipeline

---

slim/action.yml

fixes #4564
1. Use generic latest major slim version instead of hard coded specific version (major.minor.patch)

Use latest major slim version

---

docs/run-linter-locally.md

Fixes #4587
1. Fix docs on how to pull super linter docker image

Specify ghcr.io for docker location

---

README.md
docs/run-linter-locally.md

Fixes #
1. Update documentation to reference the latest version of actions/checkout

use checkout v4 in README

---

.github/release-drafter.yml

1. Put dependency updates in the maintenance section of the changelog by default

Put dependency updates in the maintenance section by default

---

README.md

1. Remove notice from april availability issue

Remove notice from april availability issue

---

Dockerfile

Fixes #4631 
1. Install golang 1.21.1 from golang Docker image

Update golang to 1.21.1

---

.github/workflows/release.yml

fixes #4650 
duplicate of https://github.com/super-linter/super-linter/pull/4694 to see if tests will pass here instead

Add exact version number to action.yml on release

---

.automation/test/go.mod

Fix https://github.com/super-linter/super-linter/issues/4631
1. Update go version of `go.mod` to 1.21.1. This is a missing implementation of https://github.com/super-linter/super-linter/pull/4677.

Update go version of go.mod

---

.github/workflows/ci.yml
README.md

Fixes #4544
1. Remove broken Codacy tool

Remove codecov reports

---

.github/workflows/cd.yml

Add tests to ensure that we test the production image as well. There's some duplication between the `ci` and the `cd` workflows at the moment.
The `cd` workflow is likely going to fail when this gets merged. Hopefully, #4773 will fix it.

Run tests against the production image

---

lib/functions/setupSSH.sh

A hotfix (not a long term) for https://github.com/super-linter/super-linter/issues/4825
1. update GitHub SSH fingerprints

update GitHub SSH fingerprints

---

.github/linters/.lintr
Dockerfile
test/inspec/super-linter/controls/super_linter.rb

Fixes #4847
1. Update to JDK 17+
2. update the google java format version

Update google java format and JDK

---

dependencies/package-lock.json
dependencies/package.json
test/inspec/super-linter/controls/super_linter.rb

Fixes #4892
1. Update Spectral dependency id to the current one.

Update spectral dependency id

---

lib/functions/buildFileList.sh

1. Change the working directory to the workspace when checking files that should be ignored by Git

Change directory when checking ignored files

---

.github/workflows/cd.yml

1. fix build cache id in the cd workflow

Fix build cache in the cd workflow

---

lib/linter.sh

1. Redact gitleaks secrets from output.

Redact gitleaks secrets from output

---

Makefile
lib/functions/buildFileList.sh
lib/linter.sh
test/lib/buildFileListTest.sh

Fixes #1167
- Fix the file diff function on push events.
- Add several tests for `GenerateFileDiff`

Fix file list diff when looking for changes

---

scripts/install-dotnet.sh

1. Switch to the LTS .NET release channel to allow .NET 8 to be installed. This is required because some new C# language features, such as collection expressions, cause `dotnet format` in .NET 7 to get confused, and it reports false problems.
`STS` restricts the version the latest Standard Term Support release, which is currently `7.0.404`:
```shell
% ./dotnet-install.sh --dry-run --channel STS
dotnet-install: Payload URLs:
dotnet-install: URL #0 - aka.ms: https://dotnetcli.azureedge.net/dotnet/Sdk/7.0.404/dotnet-sdk-7.0.404-osx-arm64.tar.gz
```
`LTS` allows latest Long Term Support release, which is currently `8.0.100`:
```text
% ./dotnet-install.sh --dry-run --channel LTS
dotnet-install: Payload URLs:
dotnet-install: URL #0 - aka.ms: …
```

Install .NET LTS instead of STS

---

Dockerfile
scripts/install-chktex.sh

- Install chktex directly instead of using a third-party container image.

Install chktex directly

---

lib/functions/validation.sh

- Fail when `USE_FIND_ALGORITHM` is true and `VALIDATE_ALL_CODEBASE` is false as expected.

Fail when validating as expected

---

Makefile
TEMPLATES/.checkov.yaml
test/inspec/super-linter/controls/super_linter.rb

- Add a default (empty) configuration file for Checkov.
- Add a smoke test to ensure that we catch the case where a default configuration file is not present, and it should be.

Add missing checkov configuration file

---

docs/upgrade-guide.md

- Write upgrade tips for Checkstyle.

Checkstyle upgrade notes

---

README.md

Fix to the README for how to run this action using the `slim` configuration.

docs: fix README.md for slim action

---

lib/functions/worker.sh

- Simplify file status checks to assume that a file should be linted correctly unless we are running in test mode.
- Avoid the corner case of files having the 'bad' string as part of their file name to be wrongly assumed to fail linting.
- Move FILE_STATUS initialization where it's needed, after running the linters.

Simplify file status checks

---

lib/functions/buildFileList.sh
lib/functions/detectFiles.sh
lib/functions/validation.sh
lib/functions/worker.sh
lib/linter.sh

- Validate variables representing boolean values.
- Group global variables in the same sections.
- Declare variables as lowercase with the 'declare -l' shell builtin for more clarity.

Validate variables and simplify lowercase

---

Dockerfile

Build the standard image starting from the base_image stage because we don't need anything from the slim image.

Standard image from base_image stage

---

Dockerfile

Run the steps to copy super-linter configs and executables in both the standard and the slim images so that we can cache the steps to install additional linters for the standard image even if we modify super-linter configs and executables.

Cache more standard image layers

---

Makefile

Fixes #4954 
**Scope**
Guarentees super-linter builds can complete linting for local run in various non-default scenarios
Implements the suggestion in #4954 to increase test coverage for `RUN_LOCAL=true` for non-default general settings into ci/cd pipeline
- Non-default Workspace: `DEFAULT_WORKSPACE`
- Git Related Env: `IGNORE_GENERATED_FILES`, `IGNORE_GITIGNORED_FILES`, `VALIDATE_ALL_CODEBASE`
- Find Algorithm: `USE_FIND_ALGORITHM`
- Non Git-tracked Directory: directory without a `.git` folder
- Experimental Features: `EXPERIMENTAL_BATCH_WORKER`
**Out of scope**
There is NO assertion for correctness of the implementation, for example
- it does not assert `find` command is used instead of `git diff` when `USE_FILE_ALGORITHM=true`
- it does not assert `.gitignored` files are not linted …

Implement two smoke tests for non-default settings

---

.textlintignore

The changelog is automatically generated, so we ignore it when running textlint because some terms might have been lowercased.

Ignore changelog when running textlint

---

.github/workflows/ci.yml

Align FILTER_REGEX_IGNORE configuration when testing the local action to the one we use in Makefile

Ignore changelog and tests when testing action

---

.github/workflows/cd.yml

Clone the repository in the release workflow otherwise we cannot create tags.
Fix #5207

Clone the repository before tagging

---

.github/workflows/ci.yml
lib/functions/buildFileList.sh
lib/functions/worker.sh
lib/linter.sh

- Check if Stdout and Stderr have elements before printing them.
- Run the super-linter action in a dedicated step using default logging to
inspect how the output looks during CI.

Check if Stdout and Stderr have elements before printing

---

.github/workflows/ci.yml
README.md
lib/functions/githubEvent.sh
lib/linter.sh
test/lib/githubEventTest.sh

Get the default branch from the GitHub Actions event payload when running on GitHub Actions. Default to 'master', as before, otherwise.
Close #4788 

Automatically set the default branch

---

lib/functions/buildFileList.sh
test/linters/xml/xsd_bad_1.xsd
test/linters/xml/xsd_good_1.xsd

Lint XSD files with xmllint
Close #5248

Lint xsd files

---

README.md

Add a notable features to the readme.

Add a notable features to the readme

---

README.md

chore(docs): fix typos in readme

---

Dockerfile

Update PSScript Analyzer from 1.21.0 to 1.22.0

Update psscript analyzer to 1.22.0

---

.github/workflows/cd.yml
.github/workflows/ci.yml

- Delete Haskell stuff
Close #5477

Free more space on workers

---

Makefile
lib/functions/buildFileList.sh
lib/linter.sh
test/lib/buildFileListTest.sh
test/run-super-linter-tests.sh

Handle initial commit

---

lib/linter.sh

Use log functions to print linter versions and the super-linter logo so that they respect the configured log level.
Close #5337

Wrap version info and logo with logs

---

lib/functions/buildFileList.sh

Find go.mod based on Go files

---

lib/functions/buildFileList.sh

Ignore avif files when building file list
Close #5382

Ignore avif files when building file list

---

docs/run-linter-locally.md

- Remove outdated Azure and GitLab references.
- Add a basic GitLab example.

Update GitLab and Azure docs

---

docs/run-linter-locally.md

Improve the instructions on the 'build locally' instructions to actually store the PAT in the local filesystem

Update run-linter-locally.md to improve build locally

---

.github/linters/.checkov-test-linters-success.yaml
.github/linters/.checkov.yaml
Dockerfile
test/inspec/super-linter/controls/super_linter.rb
test/linters/checkov/bad/bad_kustomize/graph_check.yaml
test/linters/checkov/bad/bad_kustomize/kustomization.yaml
test/linters/checkov/good/good_kustomize/graph_check.yaml
test/linters/checkov/good/good_kustomize/kustomization.yaml

Checkov needs the kustomize binary to enable related checks, otherwise these checks are silently skipped.
Ref https://www.checkov.io/7.Scan%20Examples/Kustomize.html

feat: add the kustomize binary for checkov

---

README.md
docs/run-linter-locally.md

docs: fix linting errors

---

test/linters/cloudformation/cloudformation_good_1.json
test/linters/cloudformation/cloudformation_good_2.yaml

chore: fix linting errors

---

Makefile

Run docker build checks as part of the test suite.
Ref https://docs.docker.com/reference/build-checks/

ci: run docker build checks

---

lib/linter.sh

Don't remove ENV from the list of linters to run in the slim image. Follow up to #5868

fix: update the list of linters to remove

---

lib/functions/validation.sh
lib/linter.sh
test/lib/buildFileListTest.sh
test/lib/detectFilesTest.sh
test/lib/githubEventTest.sh
test/lib/setupSSHTest.sh
test/lib/validationTest.sh

- Move USE_FIND_ALGORITHM and VALIDATE_ALL_CODEBASE validation in a dedicated function (ValidateFindMode).
- Move ANSIBLE_DIRECTORY validation to a dedicated function (ValidateAnsibleDirectory).
- Move VALIDATE_xxxx variables validation to a dedicated function (ValidateValidationVariables).
- Mark ANY_SET, ANY_TRUE, ANY_FALSE as local because we don't need to reference them anywhere outside ValidateValidationVariables.
- Add some debug statements in validation functions.
- Merge the loops to initialize VALIDATE_xxx variables and to print enable/disable language debug messages.
- Add tests for these validation functions.
- Add test start message for all tests.
I added the `Fix #ISSUE_NUMBER` or `Close #ISSUE_NUMBER` …

chore: split validation logic in smaller functions

---

.github/ISSUE_TEMPLATE/bug_report.yml

_describe the proposed changes and remove this template text_

chore: add super-linter configuration in the bug template

---

Makefile

Fix the following formatting issue seen at https://github.com/super-linter/super-linter/actions/runs/10177790966/job/28150027615 :

ci: fix output formatting

---

Makefile
test/lib/linterCommandsTest.sh

Add a test file to implement tests for `linterCommands.sh`

chore: add linter commands tests

---

test/lib/linterRulesTest.sh

Add test cases for LINTER_RULES_PATH corner cases: . and /

chore: add tests for linter rules path corner cases

---

Dockerfile
test/inspec/super-linter/controls/super_linter.rb

chore: disable dotnet telemetry

---

Dockerfile
dependencies/package-lock.json

build: run npm audit when installing dependencies

---

dependencies/package-lock.json

To resolve a security vulnerability.

chore: update micromatch dependency

---

docs/add-new-linter.md
scripts/install-checkstyle.sh
scripts/install-google-java-format.sh
scripts/install-ktlint.sh

Simplified version extract from Gradle files from 3 calls to 1. 

chore: simplified `awk` usage for version extraction

---

Dockerfile
TEMPLATES/.tflint.hcl
lib/linter.sh
test/lib/buildFileListTest.sh
test/linters/cpp/cpp_good_01.cpp
test/run-super-linter-tests.sh
test/testUtils.sh

Prepare tests for linters and formatter updates.

chore: prepare tests for updates

---

dependencies/package-lock.json

Update npm dependencies to versions without known vulnerabilities.
Close #6400

chore: update npm deps

---

test/linters/arm/arm_good_1.json

Update ARM version test in order for the test to pass.

chore: update arm test api version

---

test/linters/checkov/good/good_chart/templates/deployment.yaml
test/linters/sqlfluff/sqlfluff_good_1.sql

chore: fix checkov and sqlfluff tests

---

docs/run-linter-locally.md

Update run-linter-locally.md to include information about the default branch

---

Makefile
dependencies/package-lock.json

- Update npm dependencies in package-lock.json
- Fix dev-container mounts for package.json and package-lock.json

chore: update deps and fix devcontainer mounts

---

.github/linters/.golangci.yml
Dockerfile
lib/functions/buildFileList.sh
lib/linter.sh
test/linters/go_modules/go_modules_bad/go.mod
test/linters/go_modules/go_modules_good/go.mod

Consider Git directories safe because users might run Super-linter as an arbitrary user.
Removed other directives to mark Git directories as safe because we don't need them anymore now that Git trusts '*'.
Also, enable only the gofmt linter when running tests because we don't need other linters.

fix: consider git dirs safe

---

Dockerfile
TEMPLATES/.tflint.hcl

- PSScriptAnalyzer to 1.24.0
- TFLint plugins

chore: update dependencies

---

dependencies/python/ansible-lint.txt
dependencies/python/snakefmt.txt
dependencies/python/snakemake.txt

Update the following Python dependencies that Dependabot doesn't update:
- ansible-lint to 25.7.0
- snakefmt to 0.11.0
- snakemake to 9.9.0

chore: update python deps

---

scripts/build-venvs.sh

chore: fix requirements word typo

---

.github/workflows/ci.yml
Makefile
README.md
lib/functions/updateSSL.sh
lib/linter.sh
test/lib/updateSSLTest.sh
test/run-super-linter-tests.sh
test/testUtils.sh

- Split the test target over multiple lines
- Extend the help target regex to include help text from .PHONY entries
- Make padding of help text dynamic
- Implement assertions when providing a custom certificate

chore: simplify more tests

---

TEMPLATES/.sqlfluff

This pull request will update SQLFluff config link in [TEMPLATES/.sqlfluff](https://github.com/super-linter/super-linter/blob/main/TEMPLATES/.sqlfluff#L14) file -> https://docs.sqlfluff.com/en/stable/configuration/index.html
Close #7036

docs: update .sqlfluff config link

---

dependencies/Gemfile.lock

chore: update ruby transitive dependencies
