super-linter/super-linter

- .github/CODEOWNERS
Made this change with code spaces from my iPad which is awesome! Digital signature even worked somehow! Wow.
`CODEOWNERS` isn’t working in terms of automatically being applied to new pull requests. I think that it was because those groups that it specified are not public groups so I switched it to specify our names instead.
Signed-off-by: Zack Koppert <zkoppert@github.com>
> Specify codeowners by name

- README.md
- docs/run-linter-locally.md
- lib/linter.sh
As discussed in #98, this PR implements the logic required to enable all linters by default, but only enable the ones explicitly enabled, if any are explicitly enabled using environment variables.
The code can be tested by running:
`docker build . -t admiralawkbar/super-linter:latest` to build a new version of the container.
Then run:
`docker run -e RUN_LOCAL=true -e ACTIONS_RUNNER_DEBUG=true admiralawkbar/super-linter`, with some combination of the `VALIDATE_[LANGUAGE]` variables set to `true`, `false`, or left out.
What you should see is:
If none of the variables are added, all languages are set to true. Once either of the variables are added, that variable takes whichever value given, any variables not set are left to false.
Fixes #98
> Restructure linter flags

- README.md
Reference: https://github.com/rubocop-hq/rubocop
> Fix RuboCop capitalization in README

- README.md
* Markdown [1,2] has no capital 'd'
* CoffeeScript [3,4], JavaScript [5,6], TypeScript [7,8,9] all capitalize 'S'
* GitHub [10,11] capitalizes the 'H'
References:
[1] https://en.wikipedia.org/wiki/Markdown
[2] https://daringfireball.net/projects/markdown/syntax
[3] https://en.wikipedia.org/wiki/CoffeeScript
[4] https://coffeescript.org/
[5] https://en.wikipedia.org/wiki/JavaScript
[6] https://developer.mozilla.org/en-US/docs/Web/JavaScript
[7] https://en.wikipedia.org/wiki/TypeScript
[8] https://www.typescriptlang.org/
[9] https://github.com/Microsoft/TypeScript
[10] https://en.wikipedia.org/wiki/GitHub
[11] https://github.com/about
> Fix capitalization [skip ci]

- README.md
The previous one in the README is the URL to manage the repository (when you are the owner).
> Use public URL for the Docker container

- README.md
I used small commits for easier verification and for piecemeal use, if, say, aligning the columns was too much. Feel free to squash when merging. 
Fixes #132.
> Tweak readme linter list

- .github/CODEOWNERS
According to the following resource there's no comma separator in the CODEOWNERS file.
See: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners#codeowners-syntax
> Apply valid syntax to CODEOWNERS file

- README.md
> docs(readme): fix typo languages

- README.md
- docs/run-linter-locally.md
Now that https://github.com/github/super-linter/pull/137 has been merged, we should start pointing to it as the official image. 
cc @admiralAwkbar
> Update docs to point to github docker image

- README.md
- docs/disabling-linters.md
RuboCop is the proper notation as below.
> **RuboCop** is a Ruby static code analyzer (a.k.a. `linter`) and code formatter.
https://github.com/rubocop-hq/rubocop/blob/v0.85.1/README.md
> Update the notation of RuboCop

- Dockerfile
In setting super-linter up on one of my repo's, I ran into
golangci/golangci-lint#827 which is apparently fixed in v1.23.8 (and has
improved error messages in v1.24.0). I'm not sure if there's a reason for
using the version that is there now, but if the latest doesn't work,
please at least update to 1.24.0.
Signed-off-by: iggy <iggy@theiggy.com>
> Update to latest golangci-lint

- .github/CONTRIBUTING.md
Links pointed to github-demo which is 404, updated to point to super-linter
> Fix: Repair Links in CONTRIBUTING.MD

- .automation/test/env/README.md
- .automation/test/env/env_bad_1.env
- .automation/test/env/env_good_1.env
- Dockerfile
- README.md
- docs/disabling-linters.md
- lib/linter.sh
Added support for the linter for `.env` files (#173)  using the [dotenv-linter](https://github.com/dotenv-linter/dotenv-linter).
I also added files for tests.
> Add dotenv-linter support to super-linter

- TEMPLATES/.yaml-lint.yml
This is a very minor change. Just fixes a spelling in the yaml file.
> The word "disable" was misspelled

- README.md
Our documentation should probably prompt people to use the version that doesn't contain a bug 😅
> Advertise newest version

- lib/linter.sh
Currently the `linter.sh` file uses:
```
if [ $ERROR_CODE -ne 0 ] | [ -z "${GET_VERSION_CMD[*]}" ]; then
```
which is effectively `test | test`. This will cause the first `test` to be ignored, and only the second test's exit status will be considered. This changes it to `test || test` where it considers both
> Turn the pipe operator into the proper or operator

- docs/disabling-linters.md
Update documentation part "**Disabling linters and Rules**".
Some anchors doesn't work.
Signed-off-by: Antoine Leblanc <ant.leblanc@gmail.com>
> Update anchor for both CSS and Env linter in the table of content

- README.md
The current example is not pointing to the latest version but one which doesn't exists right now.
This can cause users to run into errors.
> Point linter.yml example to existing version

- Dockerfile
- lib/linter.sh
Hi there!
Right now, super-linter finds only these variants of `env` files:
```
foo.env
.env
```
In this PR I add support for additional variants:
```
.env.foo
.env.foo.example
```
> Add support more variants names of env files

- README.md
This addition to the `README.md` is to help clarify incoming requests about why run linting at the time of pull request (ci) instead of at the time of code writing (local).
closes https://github.com/github/super-linter/issues/204
> Add disclaimer about local development

- lib/linter.sh
When we introduced `dockerfilelint` there was no way to pass a config file, and the file needed to be in the same directory. Once we made PR to the main directory, they introduced the feature. We can now add the logic to view the `.dockerfilelintrc`
closes #285
> fixed the open Docker issue

- lib/linter.sh
`super-linter` would previously attempt to compare Clojure file endings (such as `.clj` and `.cljc`) to `$FILE`, not `$FILE_TYPE`.
When running with `VALIDATE_CLOJURE: true` for a repo containing Clojure code, this would result in warnings like these in the linting output:
```
- WARN! 
Failed to get filetype for:[project/src/my_ns.clj]!
```
And no validation of the mentioned Clojure files.
This closes #300
> Read Clojure filetypes from $FILE_TYPE, not $FILE

- .github/workflows/versioning.yml
This closes #295 by automating the creation major version tags (i.e. `v2` to point to the latest minor version of `v2.*.*`) by leveraging a new workflow file, `versioning.yml`, that uses the [actions-tagger](https://github.com/marketplace/actions/actions-tagger) action.
The end result should be that we have a latest tag and a major tag pointing to the latest release sha.
> Add actions-tagger workflow to automate version tags

- README.md
When super-linter was updated to v3, the checkout action was also (accidentally) updated to v3.
v3 of the checkout action doesn't work.
> Fix checkout action version

- docs/disabling-linters.md
The CSS link in the [disabling-linters page](https://github.com/github/super-linter/blob/master/docs/disabling-linters.md#table-of-linters) doesn't work so this PR fixes that.
> Fix CSS link

- lib/buildFileList.sh
This fixes a bug in the way we are normalizing file names during processing.
> docker should be checked in lower as it was converted

- lib/linter.sh
This PR changes the scope for the $LANGUAGE_LINTER_RULES variable so that it is seen when executing the `LintCodebase` function. Without this, the variable isn't changed outside of the `GetLinterRules` scope and therefore the default rules are applied.
Addresses the following issue: https://github.com/github/super-linter/issues/356
Possibly addresses this issue: https://github.com/github/super-linter/issues/234
> Use a global scope when setting the LANGAUGE_LINTER_RULES variable

- .github/CONTRIBUTING.md
- .github/pull_request-template.md
- .github/release-drafter.yml
- .github/workflows/draft-release.yml
fixes #203 
- Adds the release drafter action, configured to attempt to guess the next version number
- Updates documentation to request labels on all pull requests before merge
Preview of what a draft release will look like:
**Note that where it says @zkoppert, it will put the author of the change
> Auto draft releases

- lib/linter.sh
ADDED - Present user with error when attempting to pass non-directory as volume
Fixes #362 
- Provide user with error message when mounting non-directory volume
> Added check to ensure volume is directory

- lib/linter.sh
- lib/worker.sh
Fixes https://github.com/github/super-linter/issues/387
- Adjust regex for `shellcheck` lint jobs to `sh|bash|dash|ksh` extensions.
> Shellcheck other extensions

- docs/disabling-linters.md
Fixes #
minor fix for the docs to point at the correct filename for `.markdown-lint.yml`
> docs: correct name for markdown-lint

- lib/linter.sh
Fixes #368
- Removed quotes surrounding declare causing variable to not read in correctly
> Fixed config load issue caused by quotes

- lib/linter.sh
dockerfilelint's "-c" option expects a path to the folder *containing* the DOCKER_LINTER_RULES file
Based on @LukeMondy 's suggestion: https://github.com/github/super-linter/issues/305#issuecomment-651571788
Should fix #355
- Pass the path to the folder _containing_ the `DOCKER_LINTER_RULES` file, instead of the `DOCKER_LINTER_RULES` itself
See: https://github.com/replicatedhq/dockerfilelint/pull/138
> This option needs to be used with the path for the file not directly to the file. This is because https://github.com/replicatedhq/dockerfilelint/blob/master/lib/index.js#L85 adds the `.dockerfilelintrc` automatically.
> Fix dockerfilelint -c option usage

- lib/linter.sh
- lib/validation.sh
Following the logic from [here](https://github.com/github/super-linter/pull/221/files#diff-c7b422f2f140a91b67618e5aa86d8d88R477) if we don't specify any linter flag (i.e use all linters) then, editorconfig will run against the entire code base, even if there is no `.editorconfig` present, and it will even check the `.git/` folder.
In some sense this is expected because we are not specifying any linter, so all should be run. But as this one is special and lints the entire code base, I think is worth putting an extra check to only do it if either the flag is set, or `.editorconfig` is present as a special case because this behavior is different from other linters (run only against files from that extension/type).
I'm open to all feedback here. specially @mstruebing 
PD: I think another …
> Editorconfig special case

- lib/linter.sh
@admiralAwkbar:
Unfortunately commit 1da8c13a40b832bbbfd270566b54489bd2cadee8 does not work for similar reasons to those listed in @LukeMondy's comment: https://github.com/github/super-linter/issues/305#issuecomment-651571788 (I have tested with and without this commit.)
(The `GetLinterRules` function sets `LANGUAGE_LINTER_RULES` to a path including the filename again.)
I suppose we could also modify how `GetLinterRules` works, but reverting this commit seems like the easier solution - given all _other_ linters seem to expect a path *including* the filename - and fixes the use of the dockerfilelintrc file.
> **Note:** `dockerfilelint` silently proceeds with default settings if the path provided to the `-c` option doesn't match what it expects, so it's critical to test with (a) a …
> Revert "seems to be the simplier path" - Fix dockerfilelint -c option usage

- .github/dependabot.yml
- Dockerfile
- dependencies/Pipfile
- dependencies/Pipfile.lock
- dependencies/package-lock.json
- dependencies/package.json
- lib/linter.sh
- lib/worker.sh
This fixes #201 
I did a cleanup as good as I can, this is still a draft but only missing part is adding dependabot, that after #367 will only need to add npm and pyenv to the config, so I'll like feedback on the way this was done and any other comments.
About ruby, we need to fix #134 before we can start using the Gemfile properly as I stated in a comment there.
I also used what @nemchik suggested, of copy binaries from maintained docker images, for more clarity, and ease of "install"
> Use dependabot for linters dependencies

- Dockerfile
I couldn't update the existing pull request  #402 but I believe this fixes #401 
I could not make copying from the other docker image work, but I sped it up significantly by using the rakudo package for alpine linux that is from the edge/testing repo.
> Alternate approach to improve Rakudo install speed

- lib/buildFileList.sh
- lib/worker.sh
This closes #395 
This will help the linter skip the `.git/` folder as it should never really be parsed...
> small fix for git folder

- .github/workflows/stale.yml
This should correct [these](https://github.com/github/super-linter/runs/867395200?check_suite_focus=true#step:2:1) warnings
- Follow proper naming of stale bot input parameters
> Correct stale bot exempt label syntax

- action.yml
No related issue
- When a user goes to the Marketplace to add the super linter, the button shown below should guide them to use the docker image and not the dockerfile which requires a large amount of build time at each run.
low performant instructions show when you click the green button...<img width="440" alt="Screen Shot 2020-07-16 at 6 45 57 AM" src="https://user-images.githubusercontent.com/6935431/87682237-7a29ad80-c734-11ea-951b-5e850e8486ad.png">
> Use Docker instead of run-time build

- lib/worker.sh
Relates to #272 
1. Allow .yml and .yaml files to be linted
1. Globbing is not possible within quotes (http://tldp.org/LDP/abs/html/globbingref.html)
> Bash performs filename expansion on unquoted command-line arguments.
> Ansible: fix globbing issue and allow .yaml too

- Dockerfile
Fixes #
- The `COPY --from=` syntax functions correctly, but dependabot does not update it
- Use `FROM` build stages in the dockerfile so that dependabot will actually update the versions
- The last `FROM` in the dockerfile is used as the base image, any before it are used as build stages that you can copy from
- I also moved the editorconfig-checker copy line up to group it with the rest
> Adjust handling of docker dependencies

- .github/dependabot.yml
Fixes minor config error on dependabot
> Fix wrong config on dependabot

- lib/buildFileList.sh
Fixes https://github.com/github/super-linter/pull/457 (not a fix, just a follow up)
1. Use bash shell expansion to simplify the logic to extract the file extension and convert it to lowercase
No need to put my thing down flip it and reverse it.
> Simplify extension extraction

- Dockerfile
- TEMPLATES/analysis_options.yaml
- docs/disabling-linters.md
- lib/linter.sh
Fixes issues with dart pointed out in #120 
This change backs out the `pub get || true` in `linter.sh` for the following reasons:
- `pub get` should only run once
- `pub-get` should run before super-linter in it's own stage
- I'm not seeing this approach with other linters in super-linter and prefer a standardized approach
- Tests were not using `pub get` so they're were not testing the functionality/use case.
1. Calling `pub get` on each lint even with `|| true` is undesirable coupled with the fact it does not retain `+x` on copy when building `Dockerfile` (some how everything else in dart-sdk does?, not a super-linter issue). 
2. I left the glibc apk package laying around, cleaning up
3. Update wiki to reflect the `analysis_options.yaml` file
4. Doh, left the template out some how
> Dart fixes

- lib/linter.sh
Fixes case for "special types" we already do it in open api, but this is a bug for arm, open api, and cfn.
1. Use same logic as in open api
> Added case for special types like open api

- Dockerfile
This closes #454
We should never have to `lint` a Git LFS object, but a simple solution to remove the warning/error is to have the binaries installed in the system.
This should be a simple fix to the reported errors...
> Adding LFS

- docs/disabling-linters.md
On Disabling linters and Rules documentation I fixed two minor issues:
* Fix link to Clojure
* Everything after Clojure chapter was not properly defined (anymore)
* Remove surplus horizontal line
> fix disabling-linters documentation

- .automation/cleanup-docker.sh
- .automation/upload-docker.sh
Follow up from https://github.com/github/super-linter/pull/486
which caused https://github.com/github/super-linter/actions/runs/189243004 due to not being able to find the log functions.
> Fix log sources in docker scripts

- docs/disabling-linters.md
Fixes the path to `.github/linters/analysis_options.yaml`, which was misspelled in two places.
1. Fix the path to `.github/linters/analysis_options.yaml`, which was misspelled in two places.
> Fix a few typos in the Dart docs

- .automation/cleanup-docker.sh
- .automation/upload-docker.sh
Fixes https://github.com/github/super-linter/runs/946764117?check_suite_focus=true#step:3:11
1. Move log functions below global vars
2. Source log functions using `${GITHUB_WORKSPACE}` instead of relative paths
> Fix log function locations in automation

- .github/CODEOWNERS
- .github/pull_request-template.md
This will avoid confusion on who should add labels
1. Maintainers reviewing should add label before merge
2. Documentation should be included for changesets that need it
> Separate maintainer and contributor jobs

- lib/linter.sh
This closes #524 
It appears we never did the formal check for the linter rules files which helps load them into the correct locations for the tooling to properly parse...
> Adding the look

- lib/linter.sh
- lib/worker.sh
Include the `--external-sources` flag when invoking `shellcheck`.
Shellcheck supports a `--external-sources` option that allows directives like the follow to pass linting.
```
source "$(dirname "${BASH_SOURCE[0]}")/some/source/script.sh"
```
Without this option, we will see lots of spurious errors from shellcheck like the following.
```
source "$(dirname "${BASH_SOURCE[0]}")/some/source/script.sh"
^-- SC1091: Not following: SCRIPTDIR/some/source/script.sh: openBinaryFile: does not exist (No such file or directory)
```
It looks like it [may be possible](https://github.com/koalaman/shellcheck/issues/1818) to include this option in a future version of `shellcheck` through the `.shellcheckrc` configuration file, given that this issue is resolved, and that super-linter supports `.shellcheckrc` …
> Adds --external-sources option for shellcheck

- lib/buildFileList.sh
This closes #544 
- https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-comparing-branches-in-pull-requests#three-dot-and-two-dot-git-diff-comparisons
We seem to have been linting more than we wanted and the better comparison should solve the egregious overlooking...
> super slick

- lib/linter.sh
Fixes #562 
1. Fix dockerfilelint and Dockerfile Hadolint FILE_NAME variables
> Fix .dockerfilelintrc is ignored bug

- README.md
- lib/validation.sh
- lib/worker.sh
Partially fixes #472, specially [this comment](https://github.com/github/super-linter/issues/472#issuecomment-663556809)
> No validate flags = all run if found
> validate flag set to true = only validate that language
> validate flag set to false - omit only that language
I tried to keep it as simple as I could, if something is not clear, or there are better ways, any feedback is much appreciated.
1. Basically the logic described above
2. Also fixed some spelling, most of it is on another commit, so if needed can be merged on another PR
> Better VALIDATE_[LANGUAGE] vars logic

- dependencies/package-lock.json
- dependencies/package.json
GROOVY: Upgrade dependency npm-groovy-lint to version 7.3.1
Ascending compatibility is guaranteed so you can validate the PR without risks :)
> GROOVY: Upgrade npm-groovy-lint to v7.3.1

- README.md
it seems GitHub Actions now respects `actions.yml` directives when using docker actions, thus making the note to use `docker://` redundant.
in other words: using `github/superlinter@v3` no longer results in compiling the docker image, since `action.yml` has been updated 
https://github.com/github/super-linter/blob/5c75c2fdcd47301590fdd6c0c105285b8537a0dc/action.yml#L4-L6
simplify docs, and use the standard gh action format of `github/super-linter@v3`
> docs: remove note about using docker://

- lib/linter.sh
This closes #584 
We need to set the output generated folder for persistence when it defaulted to `DEFAULT_WORKSPACE`
> fix output folder for persistance

- lib/worker.sh
This closes #614 
- We need to ignore the `.venv` from Python as they should not be linted
- We need to ignore the `.rbenv`from Ruby as they should not be linted
> adding more folders to ignore

- lib/buildFileList.sh
- lib/worker.sh
This closes #659 
- We need to ignore more paths from the initial searches to prevent large load times
> Adding more paths to ignore

- .github/workflows/deploy-RELEASE.yml
1. Fixes the typo on `GPR`. I believe the original author wanted to type `GCR`.
My proposed change doesn't use `GCR` as this acronym has been generally used by the Google Container Registry. If you guys still want to use acronyms, then I suggest using `GHCR` (from your ghcr.io domain) to avoid conflicts with any existing accepted acronyms in the community.
I didn't touch other parts of the code that use `GCR` as an acronym but I can certainly do if you believe it's the right direction.
> fix: comment typo for GH Container Registry

- dependencies/package-lock.json
- dependencies/package.json
Upgrade npm-groovy-lint dependency to 7.5.1, used for Groovy linting
> Upgrade npm-groovy-lint dependency to 7.5.1

- lib/linter.sh
Fixes unexpected behavior when `DISABLE_ERRORS=true`
If a user sets `DISABLE_ERRORS=true`, they are trying to make all linting checks succeed, such that PRs can be merged even with linter failures. Unfortunately `MULTI_STATUS` doesn't respect this setting, causing builds to go red even if `DISABLE_ERRORS=true`. (To make matters worse, MULTI_STATUS is enabled by default, so right now a user will have to explicitly disable MULTI_STATUS in order for DISABLE_ERRORS to work)
This adds a bit of logic into the `MULTI_STATUS` feature which will prevent the individual statuses from failing the build when `DISABLE_ERRORS=true`.
> Making MULTI_STATUS honor DISABLE_ERRORS setting

- .automation/upload-docker.sh
- .automation/validate-docker-labels.sh
- .github/workflows/deploy-DEV.yml
- Dockerfile
- lib/linter.sh
Expose docker build arguments as environment variables to expose them when printing the header, the idea is to help to debug what's the version that has been used in case something bad happens (see https://github.com/github/super-linter/issues/672).
It has been added the git sha commit as a docker label metadata and also in the header
- ~[ ] If documentation is needed for this change, has that been included in this pull request~
> Print version, date and revision

- Dockerfile
Fixes #
1. Adds the Docker `org.opencontainers.image.source` label pointing to this repo. This label is what connects images and repositories together in GHCR
> Add org.opencontainers.image.source LABEL to Dockerfile

- TEMPLATES/.python-lint
Fixes #157 
Fixes #645
1. ignore `pylint import` errors
> added import-error to the pylint disable rules

- lib/linter.sh
Fixes #598
1. Fix getting the file name for hidden linter rule files. The solution uses [`basename`](https://linux.die.net/man/1/basename), instead of relying on multiple utilities.
2. Add a few more debug statements, so that's it's easier for users and developers understand what's going on when there are issues with rule files.
> Fix getting filename for hidden files

- README.md
1. Add documentation for users to add a badge on their repos
Benefits: 
- Coders are happy to show their code is clean 😊 
- Coders not knowing GH Super Linter will know it after have clicked on a badge 👼
> Make Super-Linter more famous with badge links on repos using it :)

- lib/buildFileList.sh
- lib/worker.sh
Fixes #704
1. Fix typos in the `find` query when building the list of files to lint.
> Fix list files function typos

- README.md
Hi folks, 
While I was reading the readme, I noticed that some links did not contain the https:// URL scheme even though the domain in the link supported SSL/TLS, so I went ahead and added the https URL scheme to those links. This is my first time opening a PR here, so hopefully I did this right 😄 
Fixes #
Changed the URL scheme in some links from http:// to https://
> Minor README improvement: https URL scheme added to some links

- lib/linter.sh
Hi folks :wave:
I was reading linter.sh to learn more about how super-linter works, and I found a typo in the code comments for the ``HTML_LINTER_RULES`` variable. The code comments referred to the ``HTML_LINTER_RULES`` variable as being the path to the CSS lint rules rather than being the path to the HTML lint rules, so I went ahead and fixed that typo.
Replaced the term "CSS" with "HTML" in code comments for the HTML_LINTER_RULES variable.
> Fixed a typo in linter.sh code comments

- dependencies/Pipfile.lock
Hi,
https://github.com/github/super-linter/commit/8ac1c99a2e5d1fa498a07f9734b2ac321a53429c downgraded black. As a result, [`v3.10.0`](https://github.com/github/super-linter/releases/tag/v3.10.0) broke existing workflow (ex: https://github.com/crytic/slither/pull/636#issuecomment-692148032). This PR restores black to its latest [available version](https://pypi.org/project/black).
Fixes #722
- Use black `20.8b1` instead of `19.10b0`
> Update black version

- lib/linter.sh
- lib/worker.sh
Fixes N/A
1. Fix the initialization of the `ERROR_ON_MISSING_EXEC_BIT` variable. We were not picking an eventually set value from the environment.
2. Add a debug statement to print the values of `ERROR_CODE`, `FILE_TYPE`, and `ERROR_ON_MISSING_EXEC_BIT`
> Fix ERROR_ON_MISSING_EXEC_BIT initialization

- .dockerignore
- .gitignore
1. Create a symbolic link to `.gitignore` named `.dockerignore`, so that we don't have to repeat ourselves.
1. Ignore the `.git` directory, so that it's ignored by the Docker daemon when building the container, because of the symbolic link above. This saves about 15-20 seconds of build time (the .git directory is currently about 20 MB in size).
> Ignore .git and symlink .dockerignore

- lib/validation.sh
1. Sort the environment variables when printing them with `printenv`. This makes debugging easier, because you don't have to manually scan the whole list looking for the variable you need to check.
> Sort environment variables when printing debug info

- lib/linter.sh
1. Lint _all_ changed files with editorconfig-checker, not just files that were detected to have the "ENV" type. Using the FILE_ARRAY_ENV seemed like a mistake honestly, I'm not sure why those files specifically should be checked against the .editorconfig. For example, previously editorconfig-checker would not be run against Javascript files if the VALIDATE_ALL_CODEBASE variable was set to false, but it would it if was set to true.
> Lint all changed files with editorconfig-checker

- lib/buildFileList.sh
- lib/linter.sh
- lib/validation.sh
1. Dynamically initialize `FILE_ARRAY` variables by iterating on the `LANGUAGES` array.
1. Remove the statically defined `FILE_ARRAY` variables.
1. Add a missing export of `LANGUAGE` variables.
1. Make each linter use its own file array.
1. Populate multiple file arrays where needed.
Note that I couldn't initialize the `FILE_ARRAY` variables in `validation.sh` because you cannot export arrays in Bash (yet).
This is a follow-up to #781 . Hopefully more PRs in this spirit are on the way!
> Dynamically initialize FILE_ARRAY variables, add a missing export

- Dockerfile
There are two `apk add` use both `--update` and `--no-cache` parameter,
which is unnecessary, usually should use only `--no-cache` to prevent
leaving cache files, just like the other `apk add` in line 249
Remove unnecessary --update for apk in Dockerfile
> Remove unnecessary --update for apk in Dockerfile

- lib/linter.sh
1. Dynamically load linter rules, so that we don't have to remember adding the call to `GetLinterRules` when adding a new language.
> Dynamically load linter rules

- .github/workflows/stack-linter.yml
- README.md
This is an update to documentation with a solution I've found to fix the issue described in #671. For the explanation please see the sample PR I created https://github.com/dec5e/super-linter-test/pull/4. Quoting important part:
> The problems seems to be in the way the code is fetched by `actions/checkout@v2` which fetches only 1 last commit by default. When I do the same locally and then do `git diff master...feature-branch` (as `super-linter` does) the command fails for me completely. Not sure why `super-linter` is not failing but it doesn't work correct either. Fetching entire git history with `actions/checkout@v2` fixes the issue.
So this looks to me like an (inconvenient) feature in a dependency action which prevents `super-linter` action to work correctly on Github. As a workaround …
> Fetch full git history to get a proper list of changed files within super-linter

- TEMPLATES/.markdown-lint.yml
Fixes #816
1. Replace `808` with `80`
> Fix probable typo in .markdown-lint.yml

- lib/linter.sh
currently, kubeval doesn't support kustomize file
so kubeval returns a false-positive about a missing `metadata` key:
```
2020-10-09 06:19:19 [ERROR ]   Found errors in [kubeval] linter!
2020-10-09 06:19:19 [ERROR ]   [ERR  - .../kustomization.yml: Missing 'metadata' key]
2020-10-09 06:19:19 [ERROR ]   Linter CMD:[kubeval --strict .../kustomization.yml]
```
> ignore kustomize file with kubeval

- dependencies/Pipfile
Pinned Black version to >=20.
https://github.com/github/super-linter/issues/807
Fixes #
Pinned version of Black formatter in Pipfile to >=20 so that it doesn't throw errors for projects using newer Black versions.
1. Pin Black version in the Pipfile
> Pinned Black version to >=20 in Pipfile

- lib/linter.sh
- lib/validation.sh
1. Use two associative arrays to initialize linter command names and linter commands.
1. Dynamically invoke linters by iterating in `LANGUAGE_ARRAY`, pulling data from the associative arrays, taking into account some exceptions, and remove the static invocations.
1. Move the `ValidatePowershellModules` to `validate.sh` and call it as part of the validation.
1. Initialize "standard rules" for javascript and typescript after the rules files path variables are ready.
1. Remove three useless calls to GetStandardRules for `clj-kondo`, `htmlhint`, and `stylelint`.
> Dynamically invoke linters

- lib/buildFileList.sh
- lib/worker.sh
This closes #830 
- We now ignore the cache folder for terragrunt as it could be full of... let's say garbage...
> remove cache folder

- dependencies/package.json
1. Install [stylelint-scss](https://github.com/kristerkari/stylelint-scss) to allow enabling SCSS rules when running stylelint.
> Install stylelint-scss

- lib/linter.sh
Fixes a small typo when a linter rule is not found.
> Fixed typo in missing linter rule fatal error.

- lib/worker.sh
1. Fix setting `FILE_STATUS` for `Dockerfile`s. Before this fix, we were assuming that if a Dockerfile didn't container the string `good` in its path, its `FILE_STATUS` should be set to `bad`. We now correctly check if a Dockerfile containts `bad` in its path to set its `FILE_STATUS` to bad.
1. Move the fallback check to set `FILE_STATUS` to `good` as the last resort. Before this fix, we had another chance to edit the FILE_STATUS after the fallback check (when checking the `Dockerfile` corner case above).
> Fix FILE_STATUS for Dockerfiles

- README.md
- docs/using-rules-files.md
Hi folks,
I added some clarity to the README that may help developers new to super-linter avoid running into issues #864 and #685. I added a "Using your own rules" section under the "Template rules" section in the README. This new section talks about how users can configure super-linter to use their own rules files if their rules files live outside of a .github/linters directory in their repo. 
I hope that this helps, or is at least a starting point that turns into documentation that helps with this issue. If anyone has any suggestions feel free to add them 😃 
cc: @pdelre, @PhunStyle, @ferrarimarco
#Fixes #864 
#Fixes #872
> README Improvement

- lib/buildFileList.sh
Fixes #900
Problem:
There is no differentiation between push and PR event type in BuildFileList function. File list gets empty when git commit pushes to DEFAULT_BRANCH.
Solution:
Make difference between push and PR requests to craft file list depends on request type
> bugfix: #900

- Dockerfile
1. Add missing dotNet dependencies: `zlib`, `zlib-dev` and `lttng-ust-dev`
1. Add missing R dependencies: `R-dev` `R-doc`, as suggested by the R installer:
>     - If you want to install R packages from CRAN that contains native extensions, then you must also install R-dev.
>     - To avoid warnings about R.css when installing R extensions also install R-doc.
This fixes warning during the installation of dotNet:
```shell
dotnet_install: Warning: Unable to locate zlib. Probable prerequisite missing; install zlib.
dotnet_install: Warning: Unable to locate liblttng. Probable prerequisite missing; install liblttng.
```
and warnings during the installation of R:
```shell
** help
No man pages found in package  ‘translations’ 
*** installing help indices
Warning in …
```
> Add missing dotnet and R dependencies

- lib/linter.sh
- lib/linterVersions.sh
Fixes #937 
1. Fail if the are errors when getting linter versions. `mapfile` was swallowing the error code, so any errors got past the validation.
1. Add a workaround for https://github.com/zaach/jsonlint/issues/122 which should be removed as soon as that issue is resolved. TLDR: `jsonlint --version` returns `1`.
> Fail on errors while getting linter versions

- Dockerfile
- lib/linter.sh
- lib/linterVersions.sh
- lib/worker.sh
Fixes #879 
1. Use the already-define linter names array while building the file list. To do this, I introduced a new variable (`WRITE_LINTER_VERSIONS_FILE`). When that variable is set to `true`, `linter.sh` runs but exists immediately after building the linter versions file. I didn't document this variable in the README because it's mostly for internal use. We can use a similar approach when we want to reuse the logic in `linter.sh`.
1. Fail hard with a `fatal` if we can't find the version of a linter, instead of a `warn`. This is useful to fail fast and doesn't impact end users because this check runs only when building the image.
1. Correct command debug output text in `worker.sh`, because we `echo` the output of commands, not the commands.
> Use the already-defined linter names array to print linter versions

- .github/ISSUE_TEMPLATE/bug_report.md
Now that super-linter is one of the popular choices for linting, I took a chance to update the `bug` issue template to guide users in providing more accurate reports.
Update the issue template for bugs:
1. Use headings instead of bold text for sections.
1. Add instructions about how to run super-linter locally to reproduce the issue.
1. Change the ask for screenshots to an ask for logs.
> Update bug issue template with logging instructions

- lib/buildFileList.sh
Fixes #954
1. Fix the exclusion of certain hidden directories that we don't want to lint from the file list.
> Fix dotdirs exclusion

- README.md
Since 'main' is the now the default for new repos moving forward, it's worth mentioning that on the README
> Mention that the default branch is usually master or main

- lib/buildFileList.sh
This closes #978 
Skip files not found on the file system...
We filter files that should have been deleted, but for some reason, we still find a few files that do not exist...
> skip files

- lib/worker.sh
This closes #968
- Adding quotes around arm and PowerShell files as the way they were used could cause spacing issues...
> quoting powershell files

- lib/functions/buildFileList.sh
Fixes #997 
1. Exclude the `__pycache__` directory from the file list. This directory [contains the compiled version of python modules](https://docs.python.org/3/tutorial/modules.html#compiled-python-files) and shouldn't be linted.
1. Exclude the `.pytest_cache` directory from the file list. This directory [contains caching for pytest tests](https://docs.pytest.org/en/latest/cache.html).
> Exclude __pycache__ and .pytest_cache from file list

- .automation/test/java/java_bad_2.java
- .automation/test/java/java_good_2.java
- .automation/test/java/reports/expected-JAVA.tap
- .github/linters/sun_checks.xml
- TEMPLATES/sun_checks.xml
1. Add a Filter and a Holder into the sun_checks.xml template to support @SuppressWarnings by default. This is triggered by a use-case of Spring Boot's default Application class failing lint because it only has a static main method. 
- [ x ] If documentation is needed for this change, has that been included in this pull request
> Enable @SuppressWarnings annotation support by default for Java

- Dockerfile
- dependencies/phive.xml
Fixes builds
1. Rakudo is now installed from the edge/community repo. It was promoted from edge/testing
2. Update phive dependencies, dependabot don't manage them, we need to keep this in mind and update them ocationally.
> Fix rakudo promote to alpine edge community repo and update phive dependencies

- TEMPLATES/.tflint.hcl
AWS rules are now optional in TFLint v0.23.0, so remove the relevant rule config.
See https://github.com/terraform-linters/tflint/releases/tag/v0.23.0
Currently, the `.tflint.hcl` means the same behavior as the default, so maybe you can remove the file.
> Tweak TFLint default config

- lib/functions/buildFileList.sh
Fixes a bug, where we checked the file existence before switching back to the branch of code (we switch to default branch previously, to pull.) so new files where been checked properly on the PRs
1. Move the switch back to the branch of code, before addif each file to the proper array
2. Change verbose level to warn, of message indicating that a files is on the commit but not on the file system. This is a warn because it alerts that something is odd, if the commit data has a file that is not in the file system something may be wrong.
> Move switch back to code branch

- Dockerfile
A tool path is specified to prevent installation of dotnet tools into /root/.dotnet/. Instead dotnet tools are installed into /var/cache/dotnet. This allows all users to access installed dotnet tools. Especially useful in unprivileged container runtimes.
Fixes #1153
1. As per documentation [dotnet tool install](https://docs.microsoft.com/de-de/dotnet/core/tools/dotnet-tool-install) the `--tool-path` option is added. See description.
> Tool path specified for dotnet tool installation

- .github/workflows/deploy-DEV.yml
- lib/functions/buildFileList.sh
- lib/linter.sh
Fixes #556
1. Improve general debug and error messages on various cases
2. Fix shallow fetch on deploy-dev action
3. Add a new test. to try the built image in the context of an action, not running it locally.
> Add debug info for multi status api calls

- lib/functions/buildFileList.sh
Fixes #
1.  revert some breaking changes, #1305 
`actions/checkout@v2` with full history will execute commands like below.  (you can reproduce using these commands)
```
$ git init
$ git remote add origin git@github.com:HatsuneMiku3939/super-linter-pr1305-test.git
$ git -c protocol.version=2 fetch --prune --progress --no-recurse-submodules origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/* +1100f8be9fbb1b5c55ee885bf7cbc5b7a1127ef7:refs/remotes//pull/1/merge
$ git checkout --progress --force refs/remotes/pull/1/merge
Note: switching to 'refs/remotes/pull/1/merge'.
...
HEAD is now at 1100f8b Merge 8316d3f11811c685b68e454b0052defdb1c8aba0 into 598eae3cae14d3aede225035dca210a7c89b732b
```
at this time, we have a no `DEFAULT_BRANCH` in local history.
```
$ git branch
* (HEAD …
```
> fix, checkout DEFAULT_BRANCH for diff base

- lib/functions/buildFileList.sh
Fixes #
1. Fix to run dotenv linter on any .env.* file, like .env.example
> Fix to lint other .env.* files

- Dockerfile
- lib/functions/worker.sh
This closes #1341
We install rust to `/tmp/` instead of `/root/` to make sure we can follow symbolic linkage
> Fix Root path for rust

- Dockerfile
This is missing since the v3.16.0 release when refactoring the Dockerfile.
Fixes: https://github.com/github/super-linter/issues/1482
Fixes #
https://github.com/github/super-linter/issues/1482
1. Install `git` and `git-lfs` in final docker image
> fix: Install git in final docker image

- lib/functions/buildFileList.sh
super-linter checks the path of the file in lib/functions/detectFiles.sh to determine whether the file is an ansible playbook. 
When VALIDATE_ALL_CODEBASE=true, a list of absolute paths is generated which matches the expected path.
When VALIDATE_ALL_CODEBASE=false, a list of relative paths is generated so no files are "detected" as ansible playbooks. 
This change outputs everything as an absolute path so diffs will also work.
> Allow ansible-lint with git diffs

- README.md
Fixes #
`CSHARP` is removed from the `slim image` but is not listed in the documentation.
Added `c#` to the `slim image` removed list in `README.md`.
> docs: added missing c# to list of slim removed langs

- lib/functions/buildFileList.sh
Add a check to the terragrunt file builder to not select packer files when it building.
This will cause terragrunt linter to stop running against packer files 
[issue1708](https://github.com/github/super-linter/issues/1708)
> Fix terragrunt file picker from selecting packer files

- lib/linter.sh
This closes #1669 
- Seems after **yamllint** `1.25` it tries to auto-detect if running in actions
-  This will tweak the command to make sure we always have output in good shape
> yamllint format

- Dockerfile-slim
This fixes small typo introduced in #1764.
Just happened to see it, hope this is not too trivial to be a PR :)
> docs(dockerfile-slim): fix typo

- lib/functions/detectFiles.sh
bats test files are shell scripts executed by bats testing system. It's widely used for testing shell scripts and CLI tools. Can just identify them as shell scripts because all corresponding linters support this format.
1. Support linting of bats files by identifying them as shell scripts (they actually are)
> feat: support bats

- Dockerfile
- Dockerfile-slim
- TEMPLATES/.tflint.hcl
This PR switches TFLint image from `wata727/tflint` to `ghcr.io/terraform-linters/tflint-bundle`.
TFLint recently migrated the image registry from Docker Hub to GitHub Container Registry. See https://github.com/terraform-linters/tflint/pull/1155
Images hosted on Docker Hub will no longer be updated.
At the same time, the image to be referenced is changed from `tflint` to `tflint-bundle` here. In the near future, We plan to deprecate the bundled plugin, and if you still need to lint your AWS resources, you'll need to install the plugin with `tflint --init`. See https://github.com/terraform-linters/tflint/pull/1160
The `tflint-bundle` image includes the latest plugins for AWS, Azure, and Google as an option to address this deprecation.
https://github.com/terraform-linters/tflint-bundle
In …
> Switch from wata727/tflint to ghcr.io/terraform-linters/tflint-bundle

- Dockerfile
- Dockerfile-slim
Follow up of https://github.com/github/super-linter/pull/1777
After checking the release of v4.5.1, I noticed that the changes I made at https://github.com/github/super-linter/pull/1777 are incomplete. The plugins under the home directory copied to `base_image` were not copied to the final stage, and as a result, it seemed that the AWS bundled plugin was used.
```console
$ sudo docker run --rm --entrypoint /bin/bash -it ghcr.io/github/super-linter:slim-v4.5.1
bash-5.1# tflint -c action/lib/.automation/.tflint.hcl -v
TFLint version 0.30.0
+ ruleset.aws (0.5.0-bundled)
```
This change prevents the bundled plugin from being used by copying the plugins to the final stage.
```console
$ sudo docker run --rm --entrypoint /bin/bash -it github/super-linter:slim
bash-5.1# tflint -c …
```
> Copy TFLint plugins to the final stage

- Dockerfile
- Dockerfile-slim
- dependencies/Pipfile
- dependencies/Pipfile.lock
- Using the black binary, vs using `pip install`
- This should allow for updated versions and stop causing issues with pip
This closes #1828
> adding black binary

- Dockerfile
- Dockerfile-slim
Fixes #1861.
1. Add a non-system, unprivileged user to the container images.
2. Set this user as default.
Since the current behavior hasn't been documented, the change doesn't have to either. It would help little to do document it now, since it is a design detail and immediately obvious when running the container (from the prompt).
> Use unprivileged user by default

- Dockerfile
- Dockerfile-slim
This reverts #1862 
We Have a loy of permission issues once this pushed.
Seems we build out of `/` dir and user has no permissions there....
This needs to be re-done and tested
> remove super-linter user due to permissions

- dependencies/package-lock.json
- dependencies/package.json
This adds `plugin:react` and `plugin:react-hooks` to eslint dependencies, which I'm hoping we can add to make super-linter even super-er 🤷 
Sorry for the huge package-lock.json update, as there is a big dependency tree for these two modules. I'm happy to try and reduce the blast radius of the lock file update, but all I did was run:
```shell
npm install eslint-plugin-react
npm install eslint-plugin-react-hooks
```
Weirdly, `eslint-plugin-react` was already in the lock file, even though it wasn't in the package.json.
> Add react and react-hooks to eslint plugins

- README.md
- slim/action.yml
Fixes #
1. Adding an sub action that can run using the slim image
> feat: adding slim action

- lib/functions/detectFiles.sh
Matching only on `"Resource": "arn` is too wide and will match also [aws json policy files](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_resource.html) for example.
Given the keys States and StartAt are required in any states file it makes sense to use one of them to narrow it down (why not even both...)
> Match AWS States file using "States" JSON key

- Dockerfile
- Dockerfile-slim
- lib/functions/buildFileList.sh
- lib/functions/detectFiles.sh
- lib/linter.sh
This closes #1920
This will add the loop to run a `composer install` if the variable `VALIDATE_PHP_PSALM` is set to `true` and we find `PHP` code to validate.
This is now added to a new loop to help with additional linters that may need some additional work before a run
> adding composer code

- Dockerfile
- Dockerfile-slim
[Release Notes](https://github.com/psf/black/releases/tag/21.9b0)
> Update black binary to 21.9b0

- .github/workflows/deploy-DEV-slim.yml
- .github/workflows/deploy-DEV-standard.yml
- .github/workflows/deploy-PROD-slim.yml
- .github/workflows/deploy-PROD-standard.yml
- .github/workflows/deploy-RELEASE-slim.yml
- .github/workflows/deploy-RELEASE-standard.yml
- .github/workflows/stale.yml
Fixes #1918 
The expression syntax used by a number of workflows is incorrect.
If you use this syntax:
```yml
if: ${{ github.event_name }} == 'schedule'
```
this will ALWAYS evaluate to true as the evaluation happens in the `${{..}}` part, and the part after the `==` is ignored.
You should instead evaluate the whole expression within the `${{..}}` parts:
```yml
if: ${{ github.event_name == 'schedule' }}
```
Or alternatively the `${{..}}` part is actually optional within `if:` statements so this works too:
```yml
if: github.event_name == 'schedule'
```
This means both parts of the stale job are run (the scheduled part which adds stale label to issue, and also removes it necessary), and the second part (which removes the stale label from the commented on issue only). This means the stale …
> Correct expressions in GitHub Actions workflows

- .github/workflows/stale.yml
Follow on from  #1952
I missed one correction when recently fixing your GitHub Action `if:` statements in #1952 so the secodn clear down step is running every night. Still better as not running on every commit and only annoying the maintainers instead of the commentators, but let's fix this one too.
> Correct Mark Not Stale job - take 2

- .github/workflows/deploy-PROD-slim.yml
- .github/workflows/deploy-PROD-standard.yml
- .github/workflows/deploy-RELEASE-slim.yml
- .github/workflows/deploy-RELEASE-standard.yml
- .github/workflows/stale.yml
Updates github-script calls to v5 syntax after dependabot upgraded this in #1996
In v5 of github-script there is [a breaking change](https://github.com/actions/github-script/pull/193) where you need to update `github.issues...` to `github.api.issues...`
At the moment the unstale script is not working for example as noted in https://github.com/github/super-linter/issues/1919#issuecomment-933120578
Also guessing your deploy scripts aren't working properly
> Fix github scripts to v5

- .github/workflows/deploy-PROD-slim.yml
- .github/workflows/deploy-PROD-standard.yml
- .github/workflows/deploy-RELEASE-slim.yml
- .github/workflows/deploy-RELEASE-standard.yml
https://github.com/github/super-linter/runs/4169311424?check_suite_focus=true#step:11:27
```
Error: Unhandled error: TypeError: Cannot read property 'issues' of undefined
```
I replace `github.api.~` in the scripts using `actions/github-script@v5` with `github.rest.~` to fix the above error.
https://github.com/actions/github-script#breaking-changes-in-v5
>Version 5 of this action includes the version 5 of `@actions/github` and `@octokit/plugin-rest-endpoint-methods`. As part of this update, the Octokit context available via `github` no longer has REST methods directly. These methods are available via `github.rest.*` - https://github.com/octokit/plugin-rest-endpoint-methods.js/releases/tag/v5.0.0
>
>For example, `github.issues.createComment` in V4 becomes `github.rest.issues.createComment` …
> Fix calling GitHub API (github.api.~ -> github.rest.~)

- .github/workflows/deploy-DEV-slim.yml
- .github/workflows/deploy-DEV-standard.yml
- .github/workflows/deploy-PROD-slim.yml
- .github/workflows/deploy-PROD-standard.yml
- .github/workflows/deploy-RELEASE-slim.yml
- .github/workflows/deploy-RELEASE-standard.yml
- .github/workflows/draft-release.yml
- .github/workflows/stack-linter.yml
- .github/workflows/stale.yml
- .github/workflows/trivy.yml
- .github/workflows/versioning.yml
I set the timeout for each CI to 1 hour because the CI deploying to production may not end.
> Add CI timeout

- README.md
- TEMPLATES/linter.yml
1. Updates the documentation link in the template to use `docs.github.com`
> Updating docs link in the template

- Dockerfile
Since `zlib` is currently distributed in `tar.zst` format, modify the Dockerfile accordingly.
FYI: https://archive.archlinux.org/packages/z/zlib/
> Fix download and uncompress zlib

- dependencies/package-lock.json
- dependencies/package.json
Fixes https://github.com/github/super-linter/issues/2221
Adds `textlint-filter-rule-allowlist` to `dependencies/package.json`.
> feat: textlint allow-list support

- lib/linter.sh
Fixes #
Use --strict for yamllint so that warnings are also picked up - as per https://yamllint.readthedocs.io/en/stable/configuration.html#errors-and-warnings we currently get a 0 return code if there are only warnings but no errors, which results in the warnings not being reported. Adding --strict brings the behaviour into line with e.g. xmllint which already returns a non-zero code for warnings only:
```
$ xmllint https://somesite.xml
warning: failed to load external entity "https://somesite.xml"
$ echo $?
1
```
> Use --strict to report yaml linting warnings

- Dockerfile
- dependencies/package-lock.json
The removal of the color.js package broke several of our dependencies.
Enabling package lock and pinning color.js until we can sort out
the color.js dep change.
Fixes #
1. ...
2. ...
3. ...
> Pin node dependencies

- README.md
- lib/linter.sh
This closes #2396 
Added the flag `YAML_ERROR_ON_WARNING` that defaults to `false`
This will remove the `--strict` that causes errors on warnings
Setting the flag to `true` will enable the `--strict` flag
> adding flag for error on warning

- lib/functions/worker.sh
This is an interesting addition...
This would now start showing the output of all linter commands on success...
It has come to the attention that some linters, such as yamllint, show warnings, but users may never be aware of them as its masked by the `0` return code and never printed.
Most outputs seem to have no real output but a `0` return code.
Some such as `GitLeaks` have returns like:
So this would cause some additional lines in the output log...
@lindluni @zkoppert @nemchik @Hanse00 @GaboFDC @ferrarimarco
Does anyone have any for or against this small but likely impactful fix?
> adding lind command output to success

- lib/functions/worker.sh
Fixes #2433
Restores or cleans up the `.terraform` folder after `tflint` runs.
This adds a caching layer to the `TERRAFORM_TFLINT` worker that keeps track of the first time a directory was seen. If an existing `.terraform` folder is that directory, then that folder will be saved to `/tmp` and restored after the `TERRAFORM_TFLINT` worker finishes. If there is no `.terraform` folder, then the `.terraform` folder that was created during linting is simply removed. This should unblock workflows that either:
* Expect no `.terraform` folder to be created by Super Linter
* Expect their existing `.terraform` folder to stay the same after Super Linter is run
This should support all the same workflows that existed before `terraform get` was added in https://github.com/github/super-linter/pull/2297 …
> fix: tflint should clean up after itself

- lib/linter.sh
Since the $GITHUB_TOKEN is required only for the multi-status feature to
work, avoid printing an error in case the feature is explicitly
disabled and we don't pass $GITHUB_TOKEN to Super-Linter.
i.e. don't print:
```
2022-02-13 14:24:13 [ERROR]   Failed to get [GITHUB_TOKEN]!
2022-02-13 14:24:13 [ERROR]   []
2022-02-13 14:24:13 [ERROR]   Please set a [GITHUB_TOKEN] from the main workflow environment to take advantage of multiple status reports!
```
when `MULTI_STATUS=false`.
> fix: don't check the $GITHUB_TOKEN if multi-status is disabled

- lib/functions/worker.sh
Echo the output only if `LINT_CMD` length is greater than `0`. This saves some output. Example:
```
2022-02-23 19:31:16 [INFO]      - Command output:
------
------
```
> Echo output only when necessary

- lib/functions/detectFiles.sh
1. Check for the presence of the `kind` key when detecting Kubernetes files to avoid including Grafana configuration files that also use the `apiVersion` key.
2. Refactor the checks in `DetectKubernetesFile` so each check analyzes the whole file content instead of the output of the previous check. This is needed because a check might strip down content making it impossible "chain" checks.
> Check for kind when detecting Kubernetes files

- Dockerfile
- I am using the Mypy type checker as part of the super linter. Mypy requires type information for packages imported by my code. For some packages it can get these by installing type stubs, which super linter supports nicely (https://github.com/github/super-linter/pull/1937), but for other packages such as Numpy and Scipy, the package itself needs to be installed. 
- I would like to be able to run `pip install numpy` inside the container, but sadly this fails, because the Python headers are missing from the container.
- One commenter https://github.com/github/super-linter/issues/157#issuecomment-648850330 suggests some ideas for how to bind external packages into the super linter, but unfortunately that will not work for Mypy, which does not check `PYTHONPATH` or other environment …
> Copy over Python headers during staged build

- lib/functions/detectFiles.sh
Fixes #2432
Fixes #2005
1. Change the name of the variable that holds the composer file path from `PATH` to `COMPOSER_PATH` to avoid overwriting the `PATH` and messing with the environment.
> Don't override the PATH when installing Psalm

- .github/workflows/draft-release.yml
- .github/workflows/repo-visualization.yml
- .github/workflows/stale.yml
- .github/workflows/trivy.yml
- .github/workflows/versioning.yml
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
> Set permissions for GitHub actions

- .automation/test/sqlfluff/.sqlfluff
- .automation/test/sqlfluff/README.md
- .github/linters/.sqlfluff
- TEMPLATES/.sqlfluff
- dependencies/python/sqlfluff.txt
Fixes #2785 
Supersedes #2779
SQLFluff 0.12.0 now requires a dialect to be set and no longer provides a default
This change:
1. Sets a default .sqlfluff config file in the `.automation/test/sqlfluff/` folder so tests can pass.
2. Updates the README in that folder to explain this
3. Updates the example config file to the latest set of options available (unrelated to above, but it was a bit out of date so included that in here).
Note Super Linter users who use SQLFluff will similarly need to configure SQLFluff now, after this upgrade is rolled out. The reasons for this breaking change are given in #2785
> SQLFluff 0.12.0 upgrade

- dependencies/package-lock.json
- dependencies/package.json
Fixes #
1. stylelint support postcss-less. 
2. stylelint support prettier.
3. ...
I found that stylelint don't support less & prettier yet.  It only support css standard, scss, scss standard.
Styleint have suggest prettier for css and postcss-less for less in the [GET START](https://stylelint.io/user-guide/get-started) of stylelint.
> chore: 🤖 stylelint support less & prettier

- .automation/test/python_black/python_bad_1.py
- .automation/test/python_black/python_good_1.py
- .automation/test/python_flake8/python_good_1.py
- .github/linters/.flake8
- TEMPLATES/.flake8
Fixes #2757
I disable `flake8` rule `E203` because this rule conflicts with `black`.
FYI: https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8
> Disable flake8 rule E203

- dependencies/package-lock.json
- dependencies/package.json
Updates NPM dependency `textlint-rule-terminology` to the latest version.
> Bump textlint-rule-terminology from 2.1.5 to 3.0.0 in /dependencies

- .github/scripts/update-npm.sh
The existence of the current lockfile can prevent some es-lint dependencies from being updating. Doing a hard remove at first ensures we don't hit the inability to resolve dependencies when auto-updating.
> Remove lockfile when updating deps

- .github/linters/.python-lint
- TEMPLATES/.python-lint
Fixes #3037 
Remove disabled checks from pylint config file, as noted in https://github.com/PyCQA/pylint/pull/4942
1. remove disabled checks from pylint config file.
> Remove disabled pylint checks from config file to work with pylint 2.14.1

- docs/run-linter-locally.md
1. Add note about `--rm` to remove the container after execution. This should prevent a build up of stopped containers after multiple runs of the super-linter
> Update run-linter-locally.md: Add note about `--rm` to remove the container after execution.

- TEMPLATES/.python-lint
Adds back import-error to the pylint disable rules that was accidentally removed in #3038 
Fixes #3180 
1. Ignore `pylint` import errors for python files
> Update pylint disable rules to include import-error

- lib/functions/worker.sh
npm-groovy-lint now accepts a list of files as arguments (and provides better performances)
To custom handling adding -path and -files is now useless so has been removed
> Remove npm-groovy-lint custom handling as it now accepts files as arguments

- lib/linter.sh
Registering the token in the log has no value, if a user pulls the token from the secret store it is automatically redacted, moreover the python scripts that drive Super Linter exit if the token is not set.
The risk is in users registering tokens by other means, such as generating app tokens at runtime where they can't be registered as secrets. Since there is all risk and no reward, remove the logging of the token.
> Stop logging token 

- dependencies/Gemfile
- dependencies/Gemfile.lock
They are both official and recommended by RuboCop itself.
1. Add `rubocop-minitest` and `minitest-rake`
> Add `rubocop-minitest` and `minitest-rake`

- .editorconfig
- Dockerfile
- dependencies/package-lock.json
- dependencies/package.json
- lib/functions/linterVersions.sh
- lib/linter.sh
- test/inspec/inspec.lock
- test/inspec/super-linter/controls/super_linter.rb
1. Don't install `actionlint` using the installation script because we already do that by copying it from its container image.
2. Install the `py3-pyflakes` package (+ relevant test) because it's needed by `actionlint`.
3. Added a missing test to verify that we install the `ca-certificates` package.
4. Fix a typo in the `.sqlfluff` file path in the InSpec test control.
5. Cherry-picked the version check for `asl-validator` from #3298
6. Configured ktlint to not expect test cases files to require PascalCase naming so that we don't have to change our test logic.
7. Update `asl-validator` to `3.0.8` by merging with #3310. This ensures that the fix we cherry-picked works and that we can update `asl-validator`. Otherwise, we're stuck in a chicken-and-egg problem. Dependabot will take care of …
> Build process improvements

- TEMPLATES/.ansible-lint.yml
Ansible Lint's YAML linting is not needed since super-linter already contains yamllint. This also fixes the conflict explained in #2818 between Ansible Lint's yamllint and super-linter's yamllint.
Fixes #2818 
1. Disable YAML linting in ansible-lint
> Disable YAML linting in ansible-lint

- README.md
1. Remove the cauldron.io report because it's not working and I we don't have administrative access to that.
> Remove non-working cauldron report

- .github/workflows/deploy-release.yml
Fixes #3384
1. Assign the `RELEASE_VERSION` variable when the workflow is manually triggered.
> Assign the RELEASE_VERSION variable

- .github/workflows/deploy-release.yml
Fixes #3411
Fixes #3412
1. Initialize the `RELEASE_VERSION` variable before using it.
2. Update the `GITHUB_ENV` variable in a single place.
3. Check if the `RELEASE_VERSION` has a value before going on.
Once this is merged, we should re-run the related workflow manually.
> Assign RELEASE_VERSION before using it

- lib/functions/detectFiles.sh
Fixes 3406
1. tflint now uses the `TFLINT_LOG` environment variable instead of the `--loglevel` switch.
> Use TFLINT_LOG environment variable instead of the deprecated --loglevel option

- .github/workflows/stack-linter.yml
1. The `Stack Linter` check is required, but it doesn't run on pushes. This PR fixes this issue by enable that check on pushes as well.
> Enable stack linter on push

- lib/functions/detectFiles.sh
1. Exit with a fatal error if `tflint --init` fails. This will help catching issues with `tflint`, such as #3406. 
This likely needs #3414 to be merged.
Update: [fails as expected](https://github.com/github/super-linter/actions/runs/3184092387/jobs/5192101429)
```
2022-10-04 17:28:19 [FATAL]   ERROR! Failed to run:[tflint --init] at location:[/tmp/lint/.automation/test]. BUILD_CMD:[Failed to parse CLI options; `loglevel` option was removed in v0.40.0. Please set `TFLINT_LOG` environment variables instead]
```
> Throw a fatal error if tflint --init fails

- dependencies/package-lock.json
- dependencies/package.json
Fixes an issue using stylelint with prettier plugin.
Can be seen as follow up to #2808. The original PR does not include the prettier plugin, which is needed to let stylelint function properly with prettier. See [stylelint prettier installation guide](https://github.com/prettier/stylelint-prettier#installation).
Fixed an error while using stylelint with prettier plugin.
> Stylelint support prettier plugin

- .github/workflows/deploy-production.yml
- Dockerfile
- Makefile
- scripts/install-arm-ttk.sh
- scripts/install-dotnet.sh
- scripts/install-kubeval.sh
- scripts/install-lintr.sh
- scripts/install-phive.sh
- scripts/install-pwsh.sh
- scripts/install-raku.sh
- scripts/install-rustfmt.sh
Pushes inline scripts in the Dockerfile into standalone scripts and authenticates requests to GitHub using a the GITHUB_TOKEN to reduce build flakiness due to GitHub's abuse and rate limiting due to unauthenticated requests.
The GITHUB_TOKEN is injected via a docker secret. The `docker` directive has been added to the Makefile which validates the user has properly set the GITHUB_TOKEN environment variable on their local machine before building.
> Push scripts into standalone files and authenticate requests

- lib/linter.sh
Make the output easier to read and more compact by doing the following:
1. Reduce the verbosity of ansible-lint.
2. Hide the Gitleaks banner (see example below).
```
○
│╲
│ ○
○ ░
░    gitleaks
```
> Don't show Gitleaks banner and Ansible-lint verbose output in output to make it more concise

- lib/functions/buildFileList.sh
add jenkinsfile to groovy files when file has no extension: eg `Jenkinsfile`
Fixes #
1. When a file `Jenkinsfile` with no extension is found, add to the Groovy files lint. This was based on the docker file `elif` check on line 425.
I don't think any additional documentation is needed for this change.
> add jenkinsfile to groovy files

- test/inspec/super-linter/controls/super_linter.rb
While calling `terraform --version` or `terraform fmt --version` produce the same output, I'd like to be explicit and call `terraform fmt --version` to monitor for changed behavior using this test.
> Add terraform_fmt to inspec tests

- README.md
- TEMPLATES/linter.yml
Addresses #3137, #3387 (and similar) by making the `permissions` requirements very clear for `MULTI_STATUS` (which is `true` by default).
[Github documentation reference](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idpermissions)
1. Add `permissions` property with `statuses: write` to base `README.MD`/`linter.yml` template
> Document GITHUB_TOKEN permissions for MULTI_STATUS to work

- .github/workflows/release.yml
- README.md
- TEMPLATES/linter.yml
- docs/run-linter-locally.md
This pull request updates internal references to the `v4` version of this repository to be `v5` with the release of `v5.0.0`.
Related to issues #4082 #4083 and #4096.
Fixes #4082 #4083 and #4096.
I simply went through the repository and manually updated references to `super-linter` `v4` to be `v5`.
1. Update `v4` references to be the latest version of the repository.
> Update all `super-linter` `v4` version references to `v5`

- README.md
One of the linter rules run against this repo requires the README start with an h1. By inserting this notice above in #4152, the linter rule has been broken. This change fixes it.
1. Bring org notice under the h1 of the README file
> Moves notice under h1

- .github/workflows/cd.yml
- .github/workflows/release.yml
This PR aims to fix syntax errors in JS scripts used by  `actions/github-script` GHA.
See failure logs due to syntax error - https://github.com/super-linter/super-linter/actions/runs/4662383130/jobs/8252663858
1. Fix syntax errors in JS scripts to avoid workflow failures.
> Fix syntax error in scripts of `actions/github-script` GHA

- lib/functions/buildFileList.sh
_This is my first time doing a pull request maybe ever, so please forgive me if I muss up something here (and give feedback, I can't improve without that)_
At work we use super-linter all over, and recently someone noticed that in the middle of a run there's a strange error that _seems_ to be fatal, and yet the code continues to run after it:
```
found item:[RUST_CLIPPY], removing linter...
fatal: unable to access 'https://github.com/MyCompany/OurRepo': Could not resolve host: github.com
2023-04-11 21:25:53 [NOTICE]   All file(s) linted successfully with no errors detected
```
As a first step, I changed logging to `TRACE`, giving me more information I could use to pinpoint where the error was:
```
2023-04-28 17:16:21 [DEBUG]   Running git config for safe dirs
2023-04-28 17:16:21 [DEBUG] …
```
> fix: Correct typo in env. var. name

- TEMPLATES/.lintr
The function `with_defaults` was deprecated in lintr version 3.0.0, which is currently installed on the super-linter image.
Use `linters_with_defaults` or `modify_defaults` instead.
> No documentation changes are needed.
> Use non-deprecated defaults for R-based linter

- CODE_OF_CONDUCT.md
An update to markdownlint in #4158 has highlighted that the current file breaks one of the rules, namely: https://github.com/updownpress/markdown-lint/blob/master/rules/034-no-bare-urls.md
This commit resolves the issue by adding angle brackets around the URL.
1. Add angle brackets around bare URL in code of conduct.
> Fixes bare URL in Code of Conduct

- lib/functions/buildFileList.sh
Fixes #
1. By checking that `IGNORE_GITIGNORED_FILES` is set to true before running `git check-ignore "$FILE"` we can prevent the git check-ignore command from being run unnecessarily.   This has the secondary benefit a not causing the following error message to be printed once per linted file outside of a git project: `fatal not a git repository (or any of the parent directories) ...`
> git check-ignore is run on every file

- .github/workflows/release.yml
fixes #4419
1. Use calculated major version instead of hardcoded v5
> Use calculated major version instead of hardcoded v5

- lib/linter.sh
Follow up to #4362
Inspired by #2031
1. If `GITHUB_DOMAIN` exists, use its value as GitHub domain
2. If `GITHUB_DOMAIN` does not exist, but `GITHUB_SERVER_URL` is already set, use its value as GitHub domain
3. If neither `GITHUB_DOMAIN` nor `GITHUB_SERVER_URL` is set, use `https://github.com` as GitHub domain
You can test the change with following configuration: 
- Update the docker image in the `action.yml` to `ghcr.io/shegox/super-linter:github-domains-2` in your testing fork
- Use it with `[your-fork]/github-super-linter@[your-branch]`
Testing with following settings in GitHub Actions:
1. GITHUB_DOMAIN=`https://github.enterprise.com`  ✅ 
2. GITHUB_DOMAIN=`github.enterprise.com`  ✅ 
3. GITHUB_DOMAIN unset ✅ 
//cc @zkoppert
> Improve GITHUB_DOMAIN/GITHUB_SERVER_URL default value handling

- lib/functions/worker.sh
Solve the deprecations introduced in tflint, which are getting removed in v0.47.0.
Unblock #4400
Change the command line call for tflint to remove the deprecations eliminated from tflint via [this PR](https://github.com/terraform-linters/tflint/pull/1687).
- [ x] If documentation is needed for this change, has that been included in this pull request
> Handle tflint deprecations

- dependencies/python/ansible-lint.txt
- dependencies/python/cfn-lint.txt
- dependencies/python/snakemake.txt
- dependencies/python/sqlfluff.txt
- dependencies/python/yamllint.txt
- dependencies/python/yq.txt
There's some conflict where PyYAML 6.0.0 and Cython 3.0 do not play well together, this version fixes that.
> Bumps PyYAML to 6.0.1

- TEMPLATES/.markdown-lint.yml
1. Typo: “far to short” ⇒ “far too short”.
2. This change is a trivial comment change.
> Fix typo on .markdown-lint.yml

- README.md
1. Changes `DEFAULT_BRANCH` to `main`. `master` is still the default, however, the README does not align with the referenced `TEMPLATES/linter.yml` which is fixed with this PR.
> Changing DEFAULT_BRANCH in README to main

- docs/run-linter-locally.md
There isn't super-linter account on Docker Hub:
https://hub.docker.com/u/super-linter
I think the image should be coming from `ghcr.io/super-linter/super-linter`
I added missing `ghcr.io/` in docs about running the super-lint locally.
1. Image tag from `super-linter/super-linter` to `ghcr.io/super-linter/super-linter`
> Fix docker image name in docs

- .automation/test/latex/latex_good_1.tex
- Dockerfile
I have updated the [chktex-alpine](https://github.com/assignUser/chktex-alpine/pkgs/container/chktex-alpine/122308127?tag=v0.2.0) package to be multi-arch with linux/arm64. I have stopped updating the package on docker hub and have switched to ghcr.io as well. This also updates chktex to version 1.7.8 from 1.7.6
> Update chktex docker image

- .github/workflows/dependabot-automation.yaml
Fixes #4647
Automate some of the dependency updates that Dependabot produces by automatically merging and approving:
- Patch updates
- Any updates to the `actions/checkout` action
- Any updates to the `docker/setup-buildx-action` action
- Any updates to the `docker/metadata-action` action
We can add more over time as we see fit by adding more conditions. To build new conditions, we can look at the metadata that Dependabot adds to commits. Example:
```yaml
---
updated-dependencies:
- dependency-name: "@typescript-eslint/eslint-plugin"
dependency-type: direct:production
update-type: version-update:semver-major
...
```
> Configure automation for dependency updates

- docs/run-linter-locally.md
The image name was missing `ghcr.io`, which caused the command to fail.
> Fix image name in run-linter-locally.md

- lib/functions/detectFiles.sh
Fixes the bug introduced in https://github.com/super-linter/super-linter/pull/3501
R package installation is _not needed_ for the R linter to work. This is called static code analysis for a reason.
Just yield a warning instead of abruptly failing the workflow if a package cannot be installed. This was the behavior for years before and worked just fine.
> Only `warn` for failure to install R packages

- .github/workflows/release.yml
Exact version pinning wont be available for super-linter until merge queue and gh cli merges are compatible. See https://github.com/cli/cli/issues/7213
1. Revert release workflow code that attempts to change the version pinned in the action.yml files
> Revert exact version pinning

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Makefile
- docs/run-linter-locally.md
Fixes #4777
Fixes #4776
1. Use the same image tags for both CI and CD workflows.
2. Dynamically set the image ID in Makefile.
3. Remove unneeded coverage report commands from Makefile.
4. Document how to run the test suite against arbitrary super-linter images.
> Use the same image tags in CI and CD

- .github/workflows/cd.yml
Fixes #4771 
Fix the CD workflow by passing the correct target when building the non-slim image.
Merge this after #4772 and #4778 to check if this fixes things.
> Fix target key in CD workflow

- lib/linter.sh
Fixes #4495
pushd to `$DEFAULT_WORKSPACE` before resolving files
> Change WORKDIR in script, not relying on docker run -w by user

- lib/functions/buildFileList.sh
Fixes #4846 
We check for files with the name (case insensitive):
- Dockerfile
- Containerfile
- <anything>.Dockerfile
- <anything>.Containerfile
This appears to protect us against catching files with a name like `Dockerfile.md`
I tested the regex like so:
> Fixes Regex to match only container files more strictly

- scripts/install-pwsh.sh
Fixes https://github.com/super-linter/super-linter/issues/4887
1. Open an issue upstream for the missing latest alpine release assets
2. Hard code latest version with alpine assets available
> Address pwsh install failure

- .github/dependabot.yml
- Dockerfile
- dependencies/checkstyle/build.gradle
- dependencies/google-java-format/build.gradle
- scripts/install-checkstyle.sh
- scripts/install-google-java-format.sh
Fixes #4893
1. Move dependency definitions for `google-java-format` and `checkstyle` to Gradle files.
2. Watch these Gradle files for updates with DependaBot
3. Dynamically fetch dependency versions from these Gradle files.
I didn't update the versions of these dependencies so that we can see if DependaBot is going to propose PRs once this is merged.
> Automatically handle Java dependencies updates

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Makefile
- lib/functions/log.sh
- lib/functions/validation.sh
- lib/linter.sh
Fixes #4952
1. Add a test case to run super-linter against a subdirectory after setting `USE_FIND_ALGORITHM=true`.
2. Move the configuration of `git safe.directory` after we set `GITHUB_WORKSPACE`, and not before because `GITHUB_WORKSPACE` might be initialized when running locally.
3. Validate variables before validating the Git repository, so that we get those variables initialized correctly before using them.
4. Validate the Git directory regardless of the value of `VALIDATE_ALL_CODEBASE` because we need a valid Git repository and references both when `VALIDATE_ALL_CODEBASE=true` and when `VALIDATE_ALL_CODEBASE=false`.
5. Validate the Git directory when `USE_FIND_ALGORITHM == false`, not when `USE_FIND_ALGORITHM != false`.
6. Initialize `GITHUB_SHA` when running locally and when …
> Don't forcefully validate Git repos if not needed

- .github/workflows/cd.yml
- .github/workflows/ci.yml
1. Populate the container image cache with the `latest` image to eventually speed up builds in case there are cache hits.
> Populate the cache with the latest image

- .github/linters/.tflint.hcl
- Dockerfile
- TEMPLATES/.tflint.hcl
- lib/functions/detectFiles.sh
- lib/functions/worker.sh
- lib/linter.sh
1. Switch from `tflint-bundle` to `tflint` because `tflint-bundle` is now deprecated.
2. Enable `azurerm` and `google` plugins by default.
3. Explicitly configure versions for plugins.
4. Define `TFLINT_LOG` and `TF_LOG_LEVEL` globally so we can reuse them anywhere we launch `tflint`.
5. Remove our tflint configuration file because the default is enough.
I didn't update tflint to the current latest version (`v0.49.0`) so we can see if dependabot picks it up.
> Switch to tflint image because tflint-bundle is deprecated

- .github/linters/commitlint.config.js
1. Dependabot doesn't allow configuring the max commit message line length until https://github.com/dependabot/dependabot-core/issues/2445 is resolved, so we cannot validate Dependabot commits at this time.
> ci: don't validate dependabot commits

- .github/release-please/release-please-config.json
- .github/workflows/cd.yml
- Dockerfile
1. Refactor Dockerfile to use a base image so that we can reuse the cache for the standard image and not just the base image.
2. Simplify the cd workflow to take into account the Production environment only for latest images.
> Use a base image and simplify environments

- .github/dependabot.yml
1. Use `deps` as the prefix for dependency updates.
> Update prefix for dependency updates

- Dockerfile
- lib/functions/detectFiles.sh
- scripts/install-lintr.sh
- scripts/install-r-package-or-fail.R
- test/inspec/super-linter/controls/super_linter.rb
Fixes #4992
1. Fail if the installation of a R package fails.
2. Install the `remotes` package once during the image build, and not when we scan files at runtime.
3. Reuse the default R library directory instead of moving it to `/home/r-library/` and installing modules there.
> Simplify lintr installation

- .github/dependabot.yml
- Dockerfile
- dependencies/ktlint/build.gradle
- scripts/install-ktlint.sh
- Automatically handle ktlint dependency updates as we did for other Java-based tools.
> feat: automatically handle ktlint updates

- .github/workflows/dependabot-automation.yaml
- Enable auto-merge for DependaBot PRs. Enabling auto-merge doesn't actually merge these PRs because we still require approvals.
> Enable auto-merge for dependabot pull requests

- docs/upgrade-guide.md
- lib/functions/validation.sh
Fixes #4956 
- Fail if the configuration contains `USE_FIND_ALGORITHM=true` and `VALIDATE_ALL_CODEBASE=false` because this is an unsupported configuration. Before this change, super-linter silently ignored `VALIDATE_ALL_CODEBASE`, leading to potentially surprising behavior.
> Validate configuration when using USE_FIND_ALGORITHM and VALIDATE_ALL_CODEBASE

- Dockerfile
- scripts/install-clj-kondo.sh
Instead of providing a script to install clj-kondo, grab it from its container image so that we can benefit from automated dependency updates.
> Install clj-kondo from its container image

- Dockerfile
- test/inspec/super-linter/controls/super_linter.rb
- Build and install clang-format instead of pulling it from a (potentially) unmaintained repository.
> Install clang-format from OS package repo

- dependencies/package-lock.json
- dependencies/package.json
- docs/upgrade-guide.md
- test/inspec/super-linter/controls/super_linter.rb
- [eslint-config-airbnb-typescript appears to be unmaintained](https://github.com/iamturns/eslint-config-airbnb-typescript/issues/314). Having it installed is blocking @typescript-eslint/eslint-plugin updates
> Uninstall eslint-config-airbnb-typescript

- .github/pull_request-template.md
- .github/workflows/ci.yml
- README.md
- lib/functions/buildFileList.sh
- lib/linter.sh
- Fix GITHUB_BEFORE_SHA initialization on push events by setting the
correct key.
- Add an additional check against setting GITHUB_BEFORE_SHA to null.
- Run the CI workflow on push events to trigger required status checks
when using the merge queue.
> Fix GITHUB_BEFORE_SHA initialization on push events

- .github/workflows/ci.yml
In order to avoid unexpected workflow cancellations due to concurrency configuration, add the event name to the concurrency group.
> Add event name to concurrency group

- Makefile
- lib/functions/detectFiles.sh
Related to #5073
- Don't run potentially expensive I/O operations to check file types if we're not going to analyze them anyway.
`make lint-subset-files-enable-only-one-type`:
```shell
real	0m21.400s
user	0m0.196s
sys	0m0.166s
```
`make lint-subset-files-enable-expensive-io-checks`:
```shell
real	0m22.722s
user	0m0.131s
sys	0m0.272s
```
> Don't inspect files if not needed

- .github/workflows/ci.yml
- Add missing '$' to github.event_name
- Default to github.head_ref (pull_request event) and fall back to github.ref (merge_group and push events)
> Fix concurrency group name

- Dockerfile
- Makefile
- test/inspec/super-linter/controls/super_linter.rb
- Build and install dependencies in dedicated stages so we can run these steps in parallel with other steps.
> Build and install dependencies in dedicated stages

- lib/functions/detectFiles.sh
- Honor SUPPRESS_FILE_TYPE_WARN when printing messages in the CheckFileType function.
- Reduce duplication when handling log messages in the CheckFileType function.
- Don't add files to the array of files to lint with JSCPD because we lint the whole codebase with JSCPD anyway.
> Handle log messages in CheckFileType

- Dockerfile
Move the invocation of the command to build the linter versions file in the slim stage because we run it again in the standard stage anyway, so there's no need for the standard stage to wait for this command to run.
> Run versions command in the slim stage

- lib/functions/buildFileList.sh
- lib/functions/githubEvent.sh
- lib/functions/linterRules.sh
- lib/functions/linterVersions.sh
- lib/linter.sh
Instead of loading the error code and checking it, shorten checks by running the command directly.
There are a couple of instances of this pattern left in updateSSL that #5130 takes care of.
> Simplify error code checks

- .github/linters/.checkov-test-linters-failure.yaml
- .github/linters/.checkov-test-linters-success.yaml
- .github/linters/.gitleaks-ignore-tests.toml
- .github/workflows/ci.yml
- .gitignore
- .gitleaksignore
- Dockerfile
- Makefile
- docs/add-new-linter.md
- docs/upgrade-guide.md
- lib/functions/buildFileList.sh
- lib/functions/detectFiles.sh
- lib/functions/linterCommands.sh
- lib/functions/log.sh
- lib/functions/validation.sh
- lib/functions/worker.sh
- lib/linter.sh
- test/inspec/super-linter/controls/super_linter.rb
- test/run-super-linter-tests.sh
- Parallelize building the file list
- Parallelize linters
- Enable Gitleaks to run against single files because it's parallelized, so there's no reason to treat it in a special way.
Fix #5073
The tasks I parallelized are, by far, the most expensive tasks. We could also parallelize the configuration of linter config files, but that takes a few seconds only.
To implement these changes, I had to refactor things a bit:
- Don't use a `.gitleaksignore` because Gitleaks doesn't provide a way to ignore this file. This was causing issues when running tests.
- Don't handle special cases to exclude `bad` and `good` tests. Use `FILTER_REGEX_EXCLUDE` and `FILTER_REGEX_INCLUDE` instead.
- Fix an issue with Checkov not linting files if the configuration file included the list of directories to lint.
- …
> Build the file list and run linters in parallel

- .github/release-please/release-please-config.json
- .textlintignore
- Makefile
CHANGELOG.md is automatically generated by the release workflow. Ignore it when linting the codebase because it might not pass textlint validation because of lowercase terms.
> Ignore changelog when linting codebase

- scripts/install-chktex.sh
Refactor the chktex installation scripts because lists of commands don't fail if one of them exits with an error, even if set -e (errexit) is set.
See the Bash reference manual, section 4.3.1 'The Set Builtin'.
Fix #5122
> Fail on errors when installing chktex

- lib/linter.sh
Remove MyPy cache after linting files so that users don't need to do as root.
Close #4822
> Remove mypy cache

- lib/functions/detectFiles.sh
MyPy expects the cache directory to be there. We now remove it after each super-linter run to avoid leftovers, so we need to create it before running MyPy.
See https://github.com/python/mypy/issues/10768
and https://github.com/python/mypy/issues/10863
> Create mypy cache directory

- Dockerfile
- Makefile
- lib/functions/buildFileList.sh
- lib/functions/detectFiles.sh
- test/inspec/super-linter/controls/super_linter.rb
- test/linters/terraform_terrascan/good/terraform-terrascan_good_2.tf
- test/run-super-linter-tests.sh
Terrascan runs initialization anyway when scanning files, so there's no point in running it at build time. Also, this works around a Terrascan bug that caused it to fail its initialization if $HOME/.terrascan directory is not present. This happens on GitHub Actions because it configures a $HOME directory that is different from ours.
> Initialize terrascan at runtime

- Makefile
- lib/functions/detectFiles.sh
- lib/functions/worker.sh
- lib/linter.sh
- test/run-super-linter-tests.sh
In case of linting errors, print stdout and stderr (if present) at the ERROR level if users set LOG_LEVEL to NOTICE to avoid failures without any explanation.
Close #5218
Worth waiting for #5249 before merging this one, so we can benefit from the test script enhancements implemented in that PR.
> Show error output when info is disabled

- .github/dependabot.yml
- dev-dependencies/Dockerfile
Consider package-lock.json when building the dev-container so we can enforce a known-working dependency chain. This caused issues in the past when commitlint and release-please had bugs in new versions  that impacted our build pipeline.
I also took the chance to revert a change to dependabot config that sneaked in a past PR.
> Take package-lock into account in dev-container

- .github/workflows/cd.yml
Set Git user and email in the CD workflow to correctly push new tags.
Fix #5283
> Configure git user and email when pushing a new release

- dependencies/package-lock.json
- dependencies/package.json
`@typescript-eslint/parser` is a transitory dependency, don't explicitly install it so it doesn't conflict with other requirements.
> Don't explicitly install typescript eslint parser

- .github/workflows/ci.yml
Dynamically build the matrix of tests to run so we can have each test in its own step without having to manually maintain the test matrix.
This makes the test suite more manageable, so we don't have to parse a gigantic log to troubleshoot CI failures.
> Dynamically build the test matrix

- lib/functions/log.sh
Correctly declare log level variables when initializing the logging infrastructure.
Fix #5218
> Fix log level variable assignment

- lib/functions/buildFileList.sh
- lib/functions/validation.sh
Emit a hopefully more helpful error message when the Git ref doesn't exist. The error message is the same we use when getting changed files only: it suggests checking that repository clone is not shallow, and that the full history is available. Additionally, when running on GitHub Actions, it also suggests checking the fetch-depth option of the actions/checkout step.
Fix #5315
> Suggest setting fetch-depth on ref errors

- .github/release-please/release-please-config.json
- lib/linter.sh
- scripts/linterVersions.sh
- Don't immediately exit on errors because this will hide diagnostic information, and linter output.
- Add documentation updates PRs to the changelog.
Fix #5335
> Don't immediately exit on errors

- scripts/install-glibc.sh
Running `install-glibc.sh` failed in ARM64, because arch linux packages doesn't offer a build for `arm64`. i.e. `https://www.archlinux.org/packages/core/arm64/zlib/download` returns a 404.
Related to #5070
> Install zlib from alpine packages

- Dockerfile
- dependencies/package-lock.json
- dependencies/package.json
- Revert "deps(npm): bump @react-native/eslint-config in /dependencies (#5417)" This reverts commit 6e35bed01240b6979036730db25219ea4d49e371.
- Enable strict npm dependency check to avoid these failures in the future.
Fix #5422
> Revert eslint-config and enable strict checks

- Dockerfile
This is similar to #3785 except in this case the high uid is for a file that does not need to be in the `super-linter` image as it is just build cache.
Pulling v6.3.0 is failing when using docker with user uid remapping:
```
failed to register layer: Container ID 197609 cannot be mapped to a host ID
```
Trying to pull with rootless podman show a more useful:
```
Error: copying system image from manifest list: writing blob: adding layer with blob "sha256:98088679e87a1114d3dafa114c911c1d8e5d33fffe624cfdd43b589a136a5f0f": ApplyLayer stdout:  stderr: potentially insufficient UIDs or GIDs available in user namespace (requested 197609:197609 for /root/.cpanm/work/1708379740.11/PPI-1.277): Check /etc/subuid and /etc/subgid if configured locally and run podman-system-migrate: lchown …
```
> Remove cpanm cache to fix uid issue when using rootless container

- lib/linter.sh
Printing the whole environment clutters the log too much. Also, it might expose sensitive information in the unlikely event that GitHub Actions don't identify certain output as secrets.
> Do not print the whole environment

- README.md
adding:
permissions: read-all
This is to avoid failure of super-linter that is triggered by `checkov`.
`checkov` flags that the top-level permissions are set to "write-all" (default value). Accordingly, the action will fail with an error.
Small addition to the yaml example as described above
> Set permissions in the README example

- .github/workflows/ci.yml
https://github.com/super-linter/super-linter/actions/runs/8676845957/job/23791768591?pr=5505
```
ConfigurationError: base (super-linter/super-linter): Missing required manifest versions: .github/release-please/.release-please-manifest.json
at fetchReleasedVersions (/app/node_modules/release-please/build/src/manifest.js:915:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async parseReleasedVersions (/app/node_modules/release-please/build/src/manifest.js:894:26)
at async Promise.all (index 1)
at async Manifest.fromManifest (/app/node_modules/release-please/build/src/manifest.js:121:93)
at async Object.handler (/app/node_modules/release-please/build/src/bin/release-please.js:319:24) {
releaserName: 'base',
repository: 'super-linter/super-linter'
}
make: …
```
> ci: do not run by pull request from fork

- .github/workflows/ci.yml
CI `preview-release-notes` do not run when PR is submitted directly.
This is probably because three or more conditions can not be connected equally in GitHub Actions' `if` statement.
Therefore, I split these.
> ci: fix a run condition in CI preview-release-notes

- .github/linters/.jscpd.json
https://github.com/super-linter/super-linter/actions/runs/8674328025/job/23786540069
```
2024-04-13 15:06:04 [INFO]   Linting JSCPD items...
2024-04-13 15:06:05 [ERROR]   Found errors when linting JSCPD. Exit code: 1.
2024-04-13 15:06:05 [INFO]   Command output for JSCPD:
------
Error: ENOENT: no such file or directory, open '/github/workspace/github_conf/branch_protection_rules.json'
at Object.openSync (node:fs:581:18)
at Object.readFileSync (node:fs:457:35)
at addContentToEntry (/node_modules/@jscpd/finder/dist/files.js:68:32)
at Array.map (<anonymous>)
at Object.getFilesToDetect (/node_modules/@jscpd/finder/dist/files.js:94:10)
at exports.detectClones (/node_modules/jscpd/dist/index.js:27:28)
at Object.<anonymous> (/node_modules/jscpd/dist/index.js:70:28)
at Generator.next …
```
> ci: ignore github_conf in jscpd

- lib/functions/log.sh
- test/run-super-linter-tests.sh
- Write log messages in the log file according to the LOG_LEVEL that the user configured (or the default), instead of printing all the messages regardless of LOG_LEVEL to the log file.
- Don't emit colors if there is no terminal
Close #5337
> Respect log level and color support when writing to the log

- TEMPLATES/.ruff.toml
- test/run-super-linter-tests.sh
- Configure Ruff to store its cache in a temporary directory inside the container by default. Users can still override this by providing a configuration file for Ruff.
- Add tests to ensure that super-linter deletes temporary files and directories.
Close #5543
> Configure ruff with a temp cache

- Makefile
- lib/linter.sh
- test/run-super-linter-tests.sh
- Don't require Git SHA and branch validation when IGNORE_GITIGNORED_FILES=true because we only need to validate that the workspace is a Git repository in this case.
Fix #5383
> No full Git validation when ignoring files

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Simplify the CI workflows by skipping GitHub deployments configuration. We don't use deployments in any other place at the moment.
> Remove deployment configuration from ci

- .github/linters/.jscpd.json
- .github/workflows/ci.yml
Move local action test to a dedicated job.
This is another step towards reducing duplication in our workflows.
> Move local action test to a dedicated job

- .github/workflows/ci.yml
- test/linters/github_actions/actions_good_01.yml
- Run a job after all the jobs in the dynamically built test matrix run to completion. This job is useful for branch protection rules that that need the whole test suite to run successfully.
- Fix linting issues.
Fix #5686
> Run a job on test suite success

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/pull_request-template.md
Given the amount of issues due to using outdated versions:
- Require users to reproduce issues with the latest Super-linter version.
- Remind users to use super-linter/super-linter, and not the deprecated github/super-linter.
> docs: update issue form to include version info

- dependencies/phive.xml
- scripts/install-phive.sh
- Composer to 2.7.6
- PHPCS to 3.10.1
- PHPStan to 1.11.2
- Psalm to 5.24.0
This also fixes the build because of outdated keys.
> deps(php): update php linters

- scripts/install-lua.sh
- Install lua and luarocks from the OS package repository instead of manually downloading them. Also the luarock fork looked unmaintained.
- Remove luarocks from the image after installing lua packages because it's not needed after that
> Install lua from the os package repository

- Dockerfile
- test/inspec/super-linter/controls/super_linter.rb
- test/linters/checkov/bad/bad_chart/Chart.yaml
- test/linters/checkov/bad/bad_chart/templates/deployment.yaml
- test/linters/checkov/bad/bad_chart/values.yaml
- test/linters/checkov/good/good_chart/Chart.yaml
- test/linters/checkov/good/good_chart/templates/deployment.yaml
- test/linters/checkov/good/good_chart/values.yaml
Includes Helm for the running of checkov scans with the helm framework
> Include Helm for checkov scans

- Makefile
- lib/functions/buildFileList.sh
- lib/functions/detectFiles.sh
- lib/functions/validation.sh
- lib/linter.sh
- test/lib/buildFileListTest.sh
- test/lib/detectFilesTest.sh
- test/lib/githubEventTest.sh
- test/lib/setupSSHTest.sh
- test/lib/validationTest.sh
Don't skip processing the current item (`FILE`) before we give `BuildFileArrays` the chance to process it as an item to eventually add to the list of directories to lint with ansible-lint.
Fix #5789
Other related changes
- Add a new make target to open a shell in a Super-linter container.
- Use a fixed path for FILE_ARRAYS_DIRECTORY_PATH so we can verify its  contents in tests
- Remove redundant ValidateBooleanVariable in buildFileList because we already check those variables in valudation.
- Move Ansible directory detection to a function so we can reuse it.
- Add missing exports for global configuration variables.
- Remove unused LOG_XXXX variables from tests. These should have been deleted when we moved log variables to log.sh
In order to have this pull request merged, complete the …
> fix: don't skip processing ansible_directory pwd

- .github/workflows/ci.yml
- Always run the job to check if any job of the test matrix failed.
- Check if any job of the test matrix was skipped or cancelled, and not just failed.
> ci: check for skipped and cancelled matrix jobs

- Dockerfile
Fix the following two warnings:
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format
> chore: fix docker build warnings

- .github/workflows/ci.yml
- Makefile
- Add information about container image layers size when printing info about the environment.
- Print info about the environment during the CI job.
This is helpful for #5630
> ci: print info about the environment, image size

- Makefile
- dev-dependencies/Dockerfile
- Run Docker build checks when building the dev-dependencies container
image and when running the test target.
- Run Docker build checks when building the Super-linter container, and
not just when running the test target.
- Use the correct variable when setting the dev-dependencies container
user.
> ci: enable dev-dependencies docker build checks

- Dockerfile
TFLint init might hit an API rate limit, especially when requests to the TFLint backend come from shared tenants, such as GitHub Actions.
> ci: authenticate tflint init

- .github/workflows/cd.yml
- Update release-please namespace because it  moved from google-github-actions to googleapis.
- Switch to a complete release identifier.
> ci: update release-please to the new workspace

- .github/dependabot.yml
Move internal-facing dependency updates out of the main changelog:
- Categorize GitHub Actions and dev dependency updates under the 'ci' prefix.
- Categorize devcontainers updates under the 'chore' prefix.
> chore: update dependabot config for ci/dev updates

- Makefile
- README.md
- lib/functions/validation.sh
- lib/linter.sh
- test/lib/validationTest.sh
- test/run-super-linter-tests.sh
- Store Super-linter outputs in the main output directory.
- Update README with a few fixes and details about outputs.
- Add missing test cases for when the configuration didn't enable any
output.
> fix: store outputs in the main output directory

- TEMPLATES/.python-lint
- test/linters/python_pylint/python_good_2.py
Adds back import-error to the pylint disable rules that was removed as of: https://github.com/super-linter/super-linter/pull/5252
Fix #5926
update .python-lint to include `disable=import-error`
Also adds a new test case for import errors
- [N/A] I wrote the necessary upgrade instructions in the [upgrade guide](../docs/upgrade-guide.md).
> fix: update pylint to ignore import-errors

- docs/upgrade-guide.md
- lib/functions/validation.sh
Document how to update the configuration when it includes JAVASCRIPT_DEFAULT_STYLE or TYPESCRIPT_DEFAULT_STYLE.
> docs: add info about standard and prettier

- docs/upgrade-guide.md
- lib/functions/linterCommands.sh
- test/lib/linterCommandsTest.sh
Add the --gitignore option to LINTER_COMMANDS_ARRAY_JSCPD when
IGNORE_GITIGNORED_FILES=true. Users can also set the gitignore options
in the Jscpd configuration file, but with this change we make Jscpd
automatically respecting that.
> feat: support ignore_gitignored_files with jscpd

- .gitignore
- Makefile
- README.md
- docs/add-new-linter.md
- docs/run-linter-locally.md
- docs/upgrade-guide.md
- lib/functions/linterCommands.sh
- lib/functions/validation.sh
- lib/functions/worker.sh
- lib/globals/linterCommandsOptions.sh
- lib/linter.sh
- test/inspec/super-linter/controls/super_linter.rb
- test/lib/linterCommandsTest.sh
- test/lib/validationTest.sh
- test/linters/groovy/groovy_good_01.groovy
- test/run-super-linter-tests.sh
- test/testUtils.sh
Certain linters and formatters support fixing linting and formatting issues (fix mode). Before this change, Super-linter runs linters and formatters in a mode that doesn't modify the source code in any way (check only mode).
With this change, Super-linter supports running linters and formatters in fix mode if explicitly requested by the configuration. If the configuration includes a variable named FIX_<language_name>, Super-linters modifies the command to run the linter or formatter for <language_name> to enable fix mode.
The modifications to the linter or formatter command that Super-linter applies depend on what is the default for a particular linter: it either removes or adds options to the command to run the linter or formatter.
In order to have this pull request merged, complete the …
> feat: local fix mode

- .devcontainer/devcontainer.json
Bind-mount the whole `lib` directory as `/action/lib` in the devcontainer so we don't have to manually add `lib` subdirectories to the devcontainer configuration as we create them.
> chore: mount the whole lib dir in the devcontainer

- .github/pull_request-template.md
Remove the H1 heading from the PR template because GitHub automatically add the commit description before emitting the PR template, so contributors don't have to manually cut-paste the commit description after the H1 heading.
> chore: remove h1 from the pr template

- Dockerfile
- test/inspec/super-linter/controls/super_linter.rb
Renovate has an optional requirement for the RE2 package, and will warn if it is not present.
Setting env variable RENOVATE_X_IGNORE_RE2=true will hide this warning.
(see https://github.com/renovatebot/renovate/pull/21391)
> fix: add RENOVATE_X_IGNORE_RE2 env var to remove warning

- .github/workflows/ci.yml
- test/run-super-linter-tests.sh
- test/testUtils.sh
- Remove test leftovers before initializing the workspace against which fix mode tests run. This prevents ownership issues.
- Pass container image build metadata as outputs of the container image build job so we can include the validate-container-image-labels target as other test target when we build the test matrix.
- Manually include the 'test' target when building the test suite matrix so we run it as part of the test suite to ensure that tests don't pollute each other's working directory.
Fix #5994
> chore: remove test leftovers before running fix test

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- scripts/build-metadata.sh
- Don't set BUILD_VERSION in CI/CD workflows otherwise the build-metadata script will always fall back to those values instead of computing new ones.
- When calculating BUILD_REVISION, check if BUILD_REVISION is set before falling back.
> build: fix build metadata

- .github/workflows/cd.yml
- .github/workflows/ci.yml
We need the whole repository history to get information about specific commits to set some build metadata, such as BUILD_VERSION.
> ci: fetch the whole repo when setting build meta

- lib/functions/buildFileList.sh
- lib/functions/worker.sh
- lib/linter.sh
Remove the initialization of FILE_ARRAY_xxx variables because worker.sh dynamically initializes them already.
> chore: remove file_array leftovers

- lib/functions/worker.sh
- lib/linter.sh
- Remove introductory text from stdout and stderr files.
- Always create stdout and stderr files, not only when there are errors.
> fix: remove intro text from stdout and stderr and always create stdout and stderr

- lib/functions/validation.sh
- lib/linter.sh
- test/lib/validationTest.sh
Reduce the number of processes to 1 if at least one FIX_xxxx variable is set to true. This avoids that Parallel runs multiple processes that might edit the same file at the same time.
> fix: avoid concurrent edits to the same file

- .devcontainer/devcontainer.json
> chore: configure prettier in the devcontainer

- README.md
> docs: add an example about fix mode on GitHub Actions

- .devcontainer/devcontainer.json
- README.md
- Add a new example about ignoring more than one file.
- Disable word wrap in the editor configured by the devcontainer.
> chore: new ignore example and set word wrap

- .devcontainer/devcontainer.json
Configure terraform formatting in the devcontainer.
> chore: configure terraform formatting

- docs/upgrade-guide.md
The jscpd documentation seems to have moved; I updated the URL to point to the correct location.
> docs: update link to jscpd documentation

- .devcontainer/devcontainer.json
- .github/CONTRIBUTING.md
- .github/pull_request-template.md
- .github/workflows/ci.yml
- CODE_OF_CONDUCT.md
- Makefile
- README.md
- TEMPLATES/README.md
- docs/add-new-linter.md
- docs/release-process.md
- docs/run-linter-locally.md
- docs/upgrade-guide.md
- prettier.config.js
- test/run-super-linter-tests.sh
- Update devcontainer by setting Prettier as a formatter only for supported languages.
- Install only the VS Code extensions that we need for Super-linter development.
- Remove the devcontainer as soon as it's not needed to avoid leaving leftovers behind.
- Enable proseWrap in Prettier configuration.
- Update documentation about how to configure new linters.
- Fix linting issues.
In retrospective, we could have avoided introducing variables to handle configuration files when the linter supported a configuration file mechanism. This would have lowered the maintenance burden on our side, and surprised users less (I think), because they can just drop Super-linter in, and it will work the same as the standalone linter in this regard, without the need of configuring Super-linter to point to …
> chore: devcontainer, docs, prettier config

- README.md
* Provide more robust regexps for ignore/exclude examples
* Drop stray backticks from `LINTER_RULES_PATH` example
> docs: Improve ignore/exclude examples

- docs/add-new-linter.md
Explain how to configure the PATH when installing new tools using pip.
> chore: explain how to configure the path

- .github/dependabot.yml
- dependencies/composer/composer.json
- dependencies/composer/composer.lock
- docs/add-new-linter.md
Group dependency update PRs in order to minimize the number of PRs to review.
Specify a PHP version in the Composer file to unblock PHP updates.
> chore: group dependency updates prs

- .gitignore
> chore: Add `.DS_Store` to `.gitignore`

- Makefile
- lib/linter.sh
- scripts/linterVersions.sh
- test/lib/linterVersionsTest.sh
Shorten the linter versions file by keeping only the version string for each linter, instead of the entire output of the version command
> chore: shorten linter versions

- .github/dependabot.yml
Add mypy to the python group when updating dependencies
> chore: add mypy to the python group

- .github/dependabot.yml
Move the python base image to a dedicated dependency group because some Python wheels might not be available for newer Python versions yet. This will avoid blocking python dependency updates waiting for wheels to be rebuilt for a given python version.
> chore: move base image to a dedicated group

- .github/workflows/ci.yml
- Dockerfile
- Makefile
Move 'npm audit' execution to a dedicated target (and corresponding step) so that we can modularize it, and avoid that it blocks that whole test suite.
> chore: move npm audit to a dedicated task

- .github/workflows/ci.yml
Don't stop the test suite on test failures, and don't skip reporting failures on certain test failures.
> chore: disable fail-fast in ci

- dependencies/package-lock.json
- dependencies/package.json
- test/linters/groovy/groovy_good_02.groovy
Fix #6371
npm-groovy-lint > 15.0.0 is impacted by:
- https://github.com/nvuillam/npm-groovy-lint/issues/428
- https://github.com/nvuillam/npm-groovy-lint/issues/422
- [ x] I followed the
> fix: downgrade npm-groovy-lint to 15.0.0

- Makefile
- lib/functions/linterCommands.sh
- lib/functions/worker.sh
- test/run-super-linter-tests.sh
Define functions in linterCommands.sh to avoid the need of exporting them. Without this fix, a command that sourced linterCommands.sh would not be able to find these functions, such as AddOptionsToCommand.
Fix #6372
> fix: define command options function before use

- scripts/git-merge-conflict-markers.sh
- test/linters/git_merge_conflict_markers/git_merge_conflict_markers_good_02.txt
The https://github.com/super-linter/super-linter/pull/6113 introduced new Git
merge conflicts linter check, that is error prone in some conditions (see
screenshot).
This PR adjusts this check to be more precise and exact in a way that all three
markers should be found to identify check as failed. Additionally improve Git
merge conflict markers matchers.
Repro:
```shell
> grep -E '^(<<<<<<<|=======|>>>>>>>)' README.md
==========================================================
=============   MegaLinter, by OX.security   =============
=========  https://ox.security?ref=megalinter  ===========
==========================================================
```
Replaces https://github.com/super-linter/super-linter/pull/6374 …
> fix: make git conflict markers check more precise

- .github/workflows/dependabot-automation.yaml
Remove the --delete-branch option in the dependency automation workflow. Ref: https://github.com/cli/cli/pull/10074
> chore: remove delete-branch option

- .github/dependabot.yml
> chore: group commitlint updates

- test/run-super-linter-tests.sh
Change ownership of files and dirs produced by Ansible because it creates directories in the working directory that are owned by the user running ansible-lint (root in this case).
> chore: fix ansible dir ownership in tests

- TEMPLATES/.stylelintrc.json
Enable stylelint-config-recommended-scss by default when linting SCSS files.
> feat: enable scss linting by default

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/stale.yml
> chore: increase workflow timeouts to 120 mins

- TEMPLATES/.golangci.yml
Remove deprecated maligned config value from the golang-ci configuration file.
Close #6120
> chore: remove deprecated golang-ci config value

- docs/run-linter-locally.md
- lib/functions/detectFiles.sh
Install dependencies with Composer when any PHP linter is enabled and there are files to lint with that linter, not just when Psalm is enabled.
Close #6336
Close #6598
Close #6597
> feat: composer install with any php linters

- Makefile
- test/inspec/super-linter/controls/super_linter.rb
> chore: fix ruby linting issues

- lib/functions/output.sh
Set Prettier output to warn unless Super-linter debug output is enabled to avoid that Prettier prints its default output when formatting the summary file, potentially confusing users.
> fix: emit prettier verbose output when debugging

- Dockerfile
- scripts/build-venvs.sh
Use python venv instead of installing virtualenv to avoid maintaining another pip requirements file.
> chore: use python venv instead of virtualenv

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Cache all the stages of the multi-stage build
> chore: cache multi-stage build

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Login to GitHub container registry before pushing stages.
> chore: login to container registry

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Makefile
Cache the base_image stage, and update the docker target in Makefile to benefit from the cache.
> chore: cache the base image stage

- lib/functions/detectFiles.sh
As "composer install with any php linters" since v7.3.0, exclude third-party libraries and improve diagnostics
Composer now always outputs complete problem descriptions by capturing the exit status separately. This ensures that even if Composer produces output on both success and failure, failures are reliably detected—replacing vague error messages with detailed explanations.
In the super-linter environment, where certain PHP extensions may be missing, Composer install now runs with the --ignore-platform-reqs flag. This prevents failures due to environment-specific missing dependencies.
Also flags --no-plugins and --no-scripts have been added to `composer install` to disable plugins and scripts during package installation or updates. This ensures that only Composer's code is executed, …
> feat: do not hide php composer output

- lib/functions/buildFileList.sh
- lib/functions/validation.sh
- lib/linter.sh
- test/lib/buildFileListTest.sh
- test/lib/validationTest.sh
- Extract the logic to initialize GITHUB_BEFORE_SHA in a function
(InitializeAndValidateGitBeforeSha).
- Set GITHUB_BEFORE_SHA for pull requests, not just for pushes. The side
effect of this is that commitlint can now lint all the commits that
are in a pull request when super-linter is triggered by a
pull_request event, instead of linting only the last commit.
- Simplify the GenerateFileDiff function by using only the git diff-tree
command (a plumbing command), for both pull requests and pushes,
instead of using the git diff-tree command for pushes, and the git
diff command (a non-plumbing command) for pull requests.
[upgrade …
> feat: set github_before_sha on pull requests

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Free disk space when building stages
Fix #6726
> chore: free disk space

- lib/functions/linterCommands.sh
- lib/globals/linterCommandsOptions.sh
- test/lib/linterCommandsTest.sh
Enables the --noout option of xmllint unless LOG_LEVEL is set to DEBUG. This avoids that xmllint emits the linted file content to stdout.
Close #6653
Credit to @thomasleplus, set as commit author.
> feat: disable xmllint verbose output if debuging

- Dockerfile
The baseline container image size for the `standard` flavor is:
- 6.04GB (v6.4.1)
- 5.94GB (v7.0.0)
- 5.87GB (v7.3.0)
- 5.89GB (097074244fb53480adb40ecd7586abda3c2246bf)
Reduce container image size, starting from 097074244fb53480adb40ecd7586abda3c2246bf:
- Remove unneeded Dart SDK components.
- Add `--production` flag to `npm install`
Size down to 5.51GB
> chore: reduce container image size

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Dockerfile
- Makefile
- dependencies/Gemfile.lock
- lib/functions/detectFiles.sh
Move ruby dependencies installation to a dedicated build stage
> chore: dedicated ruby install stage

- test/testUtils.sh
Don't use a pager when running git log to avoid that Git asks for input when running tests in an interactive shell.
> fix: do not use a pager on git log

- scripts/install-chktex.sh
> chore: retry when cloning chktex

- scripts/linterVersions.sh
Disable errexit when running the command to get the version of a linter or formatter, and enable errexit again after running that command. This allows the following error check to work as intended, and emit error messages.
> chore: disable errexit when getting versions

- .github/workflows/ci.yml
- Makefile
- lib/functions/buildFileList.sh
- test/data/test-repository-contents/json_bad_1.json
- test/lib/buildFileListTest.sh
- test/lib/validationTest.sh
- test/run-super-linter-tests.sh
- test/testUtils.sh
When linting a GitHub pull request, exclude files that don't change compared to the default branch.
Fix #6798
> fix: exclude files matching default branch ones

- TEMPLATES/.editorconfig-checker.json
Use the non-deprecated SpacesAfterTabs editorconfig-checker setting, instead of the deprecated SpacesAftertabs one.
Close #6829
> fix: use the current name for space after tabs

- docs/run-linter-locally.md
Add comprehensive documentation for running super-linter with git worktrees, including Docker mount requirements and git commands for finding the common directory. This comes in addition to #6983 while addressing #6944.
> docs: add git worktrees section to local run documentation

- Makefile
- test/lib/bashExecTest.sh
- test/lib/buildFileListTest.sh
- test/lib/linterCommandsTest.sh
- test/lib/osPackagesInstallationTest.sh
- test/run-super-linter-tests.sh
- Implement bash-exec tests instead of just running a smoke test
- Source libs from mounted files when testing functions so we don't need to rebuild the container image on each change
> chore: simplify more tests

- lib/functions/githubEvent.sh
- lib/functions/validation.sh
- lib/linter.sh
- test/lib/githubEventTest.sh
- test/lib/validationTest.sh
- test/testUtils.sh
- Handle initializing GITHUB_BEFORE_SHA on merge commits on pull_request
events by checking to which commit the DEFAULT_BRANCH is pointing at.
- Move the GIT_BEFORE_SHA validation logic in the
ValidateGitShaReference function.
- Move DEFAULT_BRANCH initialization before the GITHUB_BEFORE_SHA
initialization because the default branch might be needed to
initialize GITHUB_BEFORE_SHA.
- Move GITHUB_WORKSPACE initialization and validation logic in the
InitializeGitHubWorkspace function.
- Move GITHUB_WORKSPACE initialization before the initialization of the
DEFAULT_BRANCH variable.
Fix #6873
[upgrade …
> fix: initialize GITHUB_BEFORE_SHA on merge commits
